// <auto-generated />
using System;
using CyberPetApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CyberPetApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260609051454_AddGameAccounts")]
    partial class AddGameAccounts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CyberPetApp.Models.AutoFeeder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("FoodCount")
                        .HasColumnType("integer");

                    b.Property<int>("MaxFoodCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("AutoFeeders");
                });

            modelBuilder.Entity("CyberPetApp.Models.BackpackItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "ItemName")
                        .IsUnique();

                    b.ToTable("BackpackItems");
                });

            modelBuilder.Entity("CyberPetApp.Models.CyberCat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Energy")
                        .HasColumnType("integer");

                    b.Property<int>("Happiness")
                        .HasColumnType("integer");

                    b.Property<int>("Health")
                        .HasColumnType("integer");

                    b.Property<int>("Hunger")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Thirst")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("CyberCats");
                });

            modelBuilder.Entity("CyberPetApp.Models.FeederFood", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AutoFeederId")
                        .HasColumnType("uuid");

                    b.Property<int>("EnergyRestore")
                        .HasColumnType("integer");

                    b.Property<int>("HappinessRestore")
                        .HasColumnType("integer");

                    b.Property<int>("HungerRestore")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AutoFeederId", "SlotIndex")
                        .IsUnique();

                    b.ToTable("FeederFoods");
                });

            modelBuilder.Entity("CyberPetApp.Models.Fish", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("ActualWeight")
                        .HasColumnType("double precision");

                    b.Property<int>("EnergyRestore")
                        .HasColumnType("integer");

                    b.Property<int>("HappinessRestore")
                        .HasColumnType("integer");

                    b.Property<int>("HungerRestore")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer");

                    b.Property<int>("SellPrice")
                        .HasColumnType("integer");

                    b.Property<double>("SizePercentage")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Fishes");
                });

            modelBuilder.Entity("CyberPetApp.Models.Furniture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FurnitureId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsUnlocked")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RoomId1")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoomId1");

                    b.HasIndex("RoomId", "FurnitureId")
                        .IsUnique();

                    b.ToTable("Furnitures");
                });

            modelBuilder.Entity("CyberPetApp.Models.GameAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("GameAccounts");
                });

            modelBuilder.Entity("CyberPetApp.Models.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsWorking")
                        .HasColumnType("boolean");

                    b.Property<int>("Money")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("CyberPetApp.Models.PlayerHouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("House_Level")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerHouses");
                });

            modelBuilder.Entity("CyberPetApp.Models.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsUnlocked")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PlayerHouseId")
                        .HasColumnType("uuid");

                    b.Property<int>("UnlockPrice")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerHouseId", "Name")
                        .IsUnique();

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("CyberPetApp.Models.AutoFeeder", b =>
                {
                    b.HasOne("CyberPetApp.Models.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CyberPetApp.Models.BackpackItem", b =>
                {
                    b.HasOne("CyberPetApp.Models.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CyberPetApp.Models.CyberCat", b =>
                {
                    b.HasOne("CyberPetApp.Models.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CyberPetApp.Models.FeederFood", b =>
                {
                    b.HasOne("CyberPetApp.Models.AutoFeeder", null)
                        .WithMany()
                        .HasForeignKey("AutoFeederId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CyberPetApp.Models.Fish", b =>
                {
                    b.HasOne("CyberPetApp.Models.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CyberPetApp.Models.Furniture", b =>
                {
                    b.HasOne("CyberPetApp.Models.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CyberPetApp.Models.Room", null)
                        .WithMany("Furniture")
                        .HasForeignKey("RoomId1");
                });

            modelBuilder.Entity("CyberPetApp.Models.GameAccount", b =>
                {
                    b.HasOne("CyberPetApp.Models.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CyberPetApp.Models.PlayerHouse", b =>
                {
                    b.HasOne("CyberPetApp.Models.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CyberPetApp.Models.Room", b =>
                {
                    b.HasOne("CyberPetApp.Models.PlayerHouse", null)
                        .WithMany()
                        .HasForeignKey("PlayerHouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CyberPetApp.Models.Room", b =>
                {
                    b.Navigation("Furniture");
                });
#pragma warning restore 612, 618
        }
    }
}
