// <auto-generated by tools/gen_fishing_spots.py — do not edit by hand>
namespace CyberPetApp.Models;

public static partial class FishingSpotCatalog
{
    private static void BuildAllSpots(Dictionary<string, FishingSpot> spots)
    {
        // ── 镇外溪流 Lv1 · ×1.0 · Shallow ──
        var _镇外溪流 = new FishingSpot("镇外溪流")
        {
            FishingTime = 2,
            RequiredLevel = 1,
            PriceMultiplier = 1.0,
            PrimaryDepth = WaterDepth.Shallow,
            Description = "终端新手流域 · 浅层缓流 · 竹片与水草主产",
        };
        _镇外溪流.FishTable.AddRange([
            new FishTemplate("溪边小白条", 14, 9, 5, FishRarity.Common, 0.5, 3.0, spawnWeight: 50, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Shallow, Description = "生活在镇外溪流浅水的常见鱼类，口感普通，深受新猫咪的喜爱。" },
            new FishTemplate("土麦穗鱼", 14, 9, 5, FishRarity.Common, 1.0, 5.0, spawnWeight: 45, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Shallow, Description = "生活在镇外溪流浅水的常见鱼类，口感普通，深受新猫咪的喜爱。" },
            new FishTemplate("河湾青壳虾", 14, 9, 5, FishRarity.Common, 0.3, 1.5, spawnWeight: 55, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Shallow, Description = "生活在镇外溪流浅水区的普通小虾，外壳坚硬，肉质爽脆，极其适合作为猫咪的点心。" },
            new FishTemplate("溪底石蟹", 14, 9, 5, FishRarity.Common, 0.2, 1.0, spawnWeight: 48, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Shallow, Description = "隐蔽在镇外溪流石缝中的普通螃蟹，双螯有力，是美味的熬汤食材。" },
            new FishTemplate("野柳根子", 14, 9, 5, FishRarity.Common, 0.4, 2.0, spawnWeight: 52, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Shallow, Description = "生活在镇外溪流浅水的常见鱼类，口感普通，深受新猫咪的喜爱。" },
            new FishTemplate("宽鳍马口鱼", 14, 9, 5, FishRarity.Common, 0.3, 1.2, spawnWeight: 46, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Shallow, Description = "生活在镇外溪流浅水的常见鱼类，口感普通，深受新猫咪的喜爱。" },
            new FishTemplate("滑溜大泥鳅", 22, 13, 8, FishRarity.Rare, 0.8, 4.0, spawnWeight: 80, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Shallow, Description = "栖息于镇外溪流泥沙之中的稀有泥鳅，体表黏滑，极难徒手抓捕。" },
            new FishTemplate("野花翅子(虹鳟)", 22, 13, 8, FishRarity.Rare, 1.5, 6.0, spawnWeight: 100, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Middle, Description = "镇外溪流特产的稀有鱼类，拥有特殊的斑纹，极受老练钓手的欢迎。" },
            new FishTemplate("溪边黄石爬子", 22, 13, 8, FishRarity.Rare, 1.2, 5.5, spawnWeight: 85, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Shallow, Description = "镇外溪流特产的稀有鱼类，拥有特殊的斑纹，极受老练钓手的欢迎。" },
            new FishTemplate("精明老花鳟", 35, 19, 12, FishRarity.Epic, 1.8, 7.5, spawnWeight: 95, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Middle, Description = "极其罕见的镇外溪流史诗级大鱼，捕食习惯独特，拉竿手感异常沉重。" },
            new FishTemplate("大鳍红马口(溪哥)", 35, 19, 12, FishRarity.Epic, 2.0, 8.0, spawnWeight: 100, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Middle, Description = "极其罕见的镇外溪流史诗级大鱼，捕食习惯独特，拉竿手感异常沉重。" },
            new FishTemplate("野池红鳞锦鲤", 35, 19, 12, FishRarity.Epic, 2.2, 9.0, spawnWeight: 90, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Shallow, Description = "活跃于镇外溪流的史诗鲤鱼，鳞片金黄闪耀，常在水面掀起阵阵波澜。" },
            new FishTemplate("金背鲤仙", 50, 27, 17, FishRarity.Legendary, 2.0, 10.0, spawnWeight: 100, wariness: 0.75, power: 0.82) { PreferredDepth = WaterDepth.Shallow, Description = "活跃于镇外溪流的传说鲤鱼，鳞片金黄闪耀，常在水面掀起阵阵波澜。" },
            new FishTemplate("异变·“镜湖水虎兽”", 72, 38, 25, FishRarity.Legendary, 4.0, 18.0, spawnWeight: 120, wariness: 0.88, power: 0.94) { PreferredDepth = WaterDepth.Shallow, TargetLureRecipeId = "镇外溪流", Description = "只存在于古老传说中的lure_mutant_piranha神话神兽，受神秘饵料吸引而来，拥有不可思议的光泽与灵性。" },
            new FishTemplate("异变·“铁骨溪鳗”", 72, 38, 25, FishRarity.Legendary, 3.5, 16.0, spawnWeight: 110, wariness: 0.88, power: 0.94) { PreferredDepth = WaterDepth.Middle, TargetLureRecipeId = "镇外溪流", Description = "栖息在lure_mutant_eel暗处的神话鳗鱼，身体修长，游动姿态宛如游蛇。" },
        ]);
        spots["镇外溪流"] = _镇外溪流;

        // ── 废弃鱼塘 Lv1 · ×1.05 · Shallow ──
        var _废弃鱼塘 = new FishingSpot("废弃鱼塘")
        {
            FishingTime = 2,
            RequiredLevel = 1,
            PriceMultiplier = 1.05,
            PrimaryDepth = WaterDepth.Shallow,
            Description = "城郊人工浅塘 · 莲叶遮蔽 · 入门练竿",
        };
        _废弃鱼塘.FishTable.AddRange([
            new FishTemplate("烂泥塘鲫鱼", 14, 9, 5, FishRarity.Common, 0.4, 2.5, spawnWeight: 52, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Shallow, Description = "废弃鱼塘常见的普通鲫鱼，营养丰富，是给猫咪做鲜鱼汤的首选。" },
            new FishTemplate("腐草泥河虾", 14, 9, 5, FishRarity.Common, 0.25, 1.2, spawnWeight: 58, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Shallow, Description = "生活在废弃鱼塘浅水区的普通小虾，外壳坚硬，肉质爽脆，极其适合作为猫咪的点心。" },
            new FishTemplate("塘湾青皮黑鱼", 14, 9, 5, FishRarity.Common, 0.35, 1.8, spawnWeight: 50, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Shallow, Description = "生活在废弃鱼塘浅水的常见鱼类，口感普通，深受新猫咪的喜爱。" },
            new FishTemplate("小昂刺鱼(黄骨鱼)", 14, 9, 5, FishRarity.Common, 0.45, 2.2, spawnWeight: 48, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Shallow, Description = "生活在废弃鱼塘浅水的常见鱼类，口感普通，深受新猫咪的喜爱。" },
            new FishTemplate("浮萍野草鱼", 14, 9, 5, FishRarity.Common, 0.5, 2.8, spawnWeight: 46, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Shallow, Description = "生活在废弃鱼塘浅水的常见鱼类，口感普通，深受新猫咪的喜爱。" },
            new FishTemplate("麦穗杂鱼仔", 14, 9, 5, FishRarity.Common, 0.3, 1.5, spawnWeight: 44, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Shallow, Description = "生活在废弃鱼塘浅水的常见鱼类，口感普通，深受新猫咪的喜爱。" },
            new FishTemplate("烂泥塘大青鱼", 22, 13, 8, FishRarity.Rare, 0.9, 4.5, spawnWeight: 82, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Shallow, Description = "废弃鱼塘特产的稀有鱼类，拥有特殊的斑纹，极受老练钓手的欢迎。" },
            new FishTemplate("烂草塘毛蟹", 22, 13, 8, FishRarity.Rare, 0.7, 3.5, spawnWeight: 78, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Shallow, Description = "隐蔽在废弃鱼塘石缝中的稀有螃蟹，双螯有力，是美味的熬汤食材。" },
            new FishTemplate("红肚皮罗非鱼", 35, 19, 12, FishRarity.Epic, 1.6, 7.0, spawnWeight: 92, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Middle, Description = "极其罕见的废弃鱼塘史诗级大鱼，捕食习惯独特，拉竿手感异常沉重。" },
            new FishTemplate("胖头鳙鱼(剁椒鱼头)", 35, 19, 12, FishRarity.Epic, 1.9, 8.0, spawnWeight: 88, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Shallow, Description = "极其罕见的废弃鱼塘史诗级大鱼，捕食习惯独特，拉竿手感异常沉重。" },
            new FishTemplate("塘主·“独眼老草鱼”", 50, 27, 17, FishRarity.Legendary, 2.2, 11.0, spawnWeight: 100, wariness: 0.75, power: 0.82) { PreferredDepth = WaterDepth.Shallow, Description = "废弃鱼塘的领主级传说鱼，体形硕大，常掀起惊涛巨浪，是无数钓手追寻的目标。" },
            new FishTemplate("异变·“淤泥吞噬者”", 72, 38, 25, FishRarity.Legendary, 3.8, 15.0, spawnWeight: 115, wariness: 0.88, power: 0.94) { PreferredDepth = WaterDepth.Shallow, TargetLureRecipeId = "废弃鱼塘", Description = "只存在于古老传说中的lure_swamp_devourer神话神兽，受神秘饵料吸引而来，拥有不可思议的光泽与灵性。" },
        ]);
        spots["废弃鱼塘"] = _废弃鱼塘;

        // ── 近海礁石 Lv8 · ×1.25 · Deep ──
        var _近海礁石 = new FishingSpot("近海礁石")
        {
            FishingTime = 2,
            RequiredLevel = 8,
            PriceMultiplier = 1.25,
            PrimaryDepth = WaterDepth.Deep,
            Description = "离岸雾墙 · 磷光深海 · 碳纤维主产",
            FishRarityTable = new()
            {
                { FishRarity.Common, 55 },
                { FishRarity.Rare, 25 },
                { FishRarity.Epic, 14 },
                { FishRarity.Legendary, 6 }
            }
        };
        _近海礁石.FishTable.AddRange([
            new FishTemplate("浪击海鲈鱼", 14, 9, 5, FishRarity.Common, 1.0, 5.0, spawnWeight: 40, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Deep, Description = "生活在近海礁石水流中的普通鲈鱼，背鳍锐利，肉质肥嫩鲜美。" },
            new FishTemplate("礁影红加吉鱼", 14, 9, 5, FishRarity.Common, 0.5, 3.0, spawnWeight: 60, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Deep, Description = "生活在近海礁石深海的常见鱼类，口感普通，深受新猫咪的喜爱。" },
            new FishTemplate("沙蚕爬虫", 14, 9, 5, FishRarity.Common, 0.4, 2.0, spawnWeight: 50, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Shallow, Description = "生活在近海礁石浅水的常见鱼类，口感普通，深受新猫咪的喜爱。" },
            new FishTemplate("小透明鱿鱼仔", 14, 9, 5, FishRarity.Common, 0.5, 2.5, spawnWeight: 55, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Middle, Description = "近海礁石的普通软体动物，体型柔软，能喷射荧光墨汁逃避掠食者。" },
            new FishTemplate("礁石小红虾", 14, 9, 5, FishRarity.Common, 0.3, 1.5, spawnWeight: 48, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Deep, Description = "生活在近海礁石深海区的普通小虾，外壳坚硬，肉质爽脆，极其适合作为猫咪的点心。" },
            new FishTemplate("小海鳗苗", 14, 9, 5, FishRarity.Common, 0.45, 2.2, spawnWeight: 46, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Deep, Description = "栖息在近海礁石暗处的普通鳗鱼，身体修长，游动姿态宛如游蛇。" },
            new FishTemplate("荧光墨鱼", 22, 13, 8, FishRarity.Rare, 1.0, 7.0, spawnWeight: 100, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Middle, Description = "近海礁石特产的稀有鱼类，拥有特殊的斑纹，极受老练钓手的欢迎。" },
            new FishTemplate("乱石堆电鳗", 22, 13, 8, FishRarity.Rare, 1.5, 9.0, spawnWeight: 90, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Deep, Description = "栖息在近海礁石暗处的稀有鳗鱼，身体修长，游动姿态宛如游蛇。" },
            new FishTemplate("小银剪子(银鳍枪鱼)", 22, 13, 8, FishRarity.Rare, 1.3, 8.0, spawnWeight: 85, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Deep, Description = "近海礁石特产的稀有鱼类，拥有特殊的斑纹，极受老练钓手的欢迎。" },
            new FishTemplate("烈焰红仙子", 22, 13, 8, FishRarity.Rare, 1.1, 6.5, spawnWeight: 80, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Middle, Description = "近海礁石特产的稀有鱼类，拥有特殊的斑纹，极受老练钓手的欢迎。" },
            new FishTemplate("大灯笼安康鱼", 35, 19, 12, FishRarity.Epic, 3.0, 12.0, spawnWeight: 100, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep, Description = "生活在近海礁石深渊处的史诗安康鱼，头顶挂有发光灯笼，长相奇特。" },
            new FishTemplate("深水魔鬼鳐", 35, 19, 12, FishRarity.Epic, 2.5, 15.0, spawnWeight: 85, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep, Description = "生活在近海礁石的史诗鳐鱼，身形如扁平飞翼，在水层中优雅滑翔。" },
            new FishTemplate("巨型软丝鱿", 35, 19, 12, FishRarity.Epic, 2.8, 13.0, spawnWeight: 92, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep, Description = "近海礁石的史诗软体动物，体型柔软，能喷射荧光墨汁逃避掠食者。" },
            new FishTemplate("斑斓大石斑", 50, 27, 17, FishRarity.Legendary, 2.0, 10.0, spawnWeight: 100, wariness: 0.75, power: 0.82) { PreferredDepth = WaterDepth.Deep, Description = "近海礁石的领主级传说鱼，体形硕大，常掀起惊涛巨浪，是无数钓手追寻的目标。" },
            new FishTemplate("异变·“雾海古神鱿”", 72, 38, 25, FishRarity.Legendary, 5.0, 22.0, spawnWeight: 120, wariness: 0.88, power: 0.94) { PreferredDepth = WaterDepth.Deep, TargetLureRecipeId = "近海礁石", Description = "lure_giant_squid的神话软体动物，体型柔软，能喷射荧光墨汁逃避掠食者。" },
        ]);
        spots["近海礁石"] = _近海礁石;

        // ── 芦苇湿地 Lv12 · ×1.3 · Shallow ──
        var _芦苇湿地 = new FishingSpot("芦苇湿地")
        {
            FishingTime = 2,
            RequiredLevel = 12,
            PriceMultiplier = 1.3,
            PrimaryDepth = WaterDepth.Shallow,
            Description = "芦苇荡浅湾 · 风噪掩蔽 · 老韧芦苇丝副产",
            FishRarityTable = new()
            {
                { FishRarity.Common, 52 },
                { FishRarity.Rare, 28 },
                { FishRarity.Epic, 14 },
                { FishRarity.Legendary, 6 }
            }
        };
        _芦苇湿地.FishTable.AddRange([
            new FishTemplate("老芦苇青鲫", 14, 9, 5, FishRarity.Common, 0.5, 2.8, spawnWeight: 50, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Shallow, Description = "芦苇湿地常见的普通鲫鱼，营养丰富，是给猫咪做鲜鱼汤的首选。" },
            new FishTemplate("浅滩青虾", 14, 9, 5, FishRarity.Common, 0.3, 1.6, spawnWeight: 54, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Shallow, Description = "生活在芦苇湿地浅水区的普通小虾，外壳坚硬，肉质爽脆，极其适合作为猫咪的点心。" },
            new FishTemplate("芦苇根小泥鳅", 14, 9, 5, FishRarity.Common, 0.4, 2.0, spawnWeight: 48, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Shallow, Description = "栖息于芦苇湿地泥沙之中的普通泥鳅，体表黏滑，极难徒手抓捕。" },
            new FishTemplate("风纹白鲫", 14, 9, 5, FishRarity.Common, 0.55, 3.0, spawnWeight: 46, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Shallow, Description = "芦苇湿地常见的普通鲫鱼，营养丰富，是给猫咪做鲜鱼汤的首选。" },
            new FishTemplate("湿地圆螃蟹", 14, 9, 5, FishRarity.Common, 0.35, 1.8, spawnWeight: 52, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Shallow, Description = "隐蔽在芦苇湿地石缝中的普通螃蟹，双螯有力，是美味的熬汤食材。" },
            new FishTemplate("芦花游鲦", 14, 9, 5, FishRarity.Common, 0.28, 1.4, spawnWeight: 44, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Middle, Description = "生活在芦苇湿地中层的常见鱼类，口感普通，深受新猫咪的喜爱。" },
            new FishTemplate("野性湿地鲈", 22, 13, 8, FishRarity.Rare, 1.1, 5.5, spawnWeight: 88, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Middle, Description = "生活在芦苇湿地水流中的稀有鲈鱼，背鳍锐利，肉质肥嫩鲜美。" },
            new FishTemplate("苇荡鳜鱼", 22, 13, 8, FishRarity.Rare, 1.3, 6.5, spawnWeight: 85, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Shallow, Description = "芦苇湿地特产的稀有鱼类，拥有特殊的斑纹，极受老练钓手的欢迎。" },
            new FishTemplate("逆流银大鲑", 22, 13, 8, FishRarity.Rare, 1.4, 7.0, spawnWeight: 82, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Middle, Description = "芦苇湿地特产的稀有鱼类，拥有特殊的斑纹，极受老练钓手的欢迎。" },
            new FishTemplate("泥沼黄斑大鲶", 35, 19, 12, FishRarity.Epic, 2.2, 10.0, spawnWeight: 95, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep, Description = "极其罕见的芦苇湿地史诗级大鱼，捕食习惯独特，拉竿手感异常沉重。" },
            new FishTemplate("湿地黄姑子", 35, 19, 12, FishRarity.Epic, 2.0, 9.5, spawnWeight: 90, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Middle, Description = "极其罕见的芦苇湿地史诗级大鱼，捕食习惯独特，拉竿手感异常沉重。" },
            new FishTemplate("湿地老青鲩", 50, 27, 17, FishRarity.Legendary, 2.5, 12.0, spawnWeight: 100, wariness: 0.75, power: 0.82) { PreferredDepth = WaterDepth.Shallow, Description = "芦苇湿地的领主级传说鱼，体形硕大，常掀起惊涛巨浪，是无数钓手追寻的目标。" },
            new FishTemplate("异变·“毒沼鳄王”", 72, 38, 25, FishRarity.Legendary, 4.2, 17.0, spawnWeight: 118, wariness: 0.88, power: 0.94) { PreferredDepth = WaterDepth.Middle, TargetLureRecipeId = "芦苇湿地", Description = "只存在于古老传说中的lure_poison_croc神话神兽，受神秘饵料吸引而来，拥有不可思议的光泽与灵性。" },
        ]);
        spots["芦苇湿地"] = _芦苇湿地;

        // ── 地下暗河 Lv18 · ×1.5 · Middle ──
        var _地下暗河 = new FishingSpot("地下暗河")
        {
            FishingTime = 2,
            RequiredLevel = 18,
            PriceMultiplier = 1.5,
            PrimaryDepth = WaterDepth.Middle,
            Description = "荧光运河 · 中层夜钓 · 荧光粉主产",
            FishRarityTable = new()
            {
                { FishRarity.Common, 50 },
                { FishRarity.Rare, 28 },
                { FishRarity.Epic, 16 },
                { FishRarity.Legendary, 6 }
            }
        };
        _地下暗河.FishTable.AddRange([
            new FishTemplate("盲眼发光鲤", 14, 9, 5, FishRarity.Common, 0.8, 4.0, spawnWeight: 50, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Middle, Description = "活跃于地下暗河的普通鲤鱼，鳞片金黄闪耀，常在水面掀起阵阵波澜。" },
            new FishTemplate("暗河玻璃蝌蚪", 14, 9, 5, FishRarity.Common, 0.4, 2.0, spawnWeight: 55, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Shallow, Description = "生活在地下暗河浅水的常见鱼类，口感普通，深受新猫咪的喜爱。" },
            new FishTemplate("暗河透明虾", 14, 9, 5, FishRarity.Common, 0.3, 1.8, spawnWeight: 52, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Shallow, Description = "生活在地下暗河浅水区的普通小虾，外壳坚硬，肉质爽脆，极其适合作为猫咪的点心。" },
            new FishTemplate("暗河长须鲫", 14, 9, 5, FishRarity.Common, 0.6, 3.0, spawnWeight: 48, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Shallow, Description = "地下暗河常见的普通鲫鱼，营养丰富，是给猫咪做鲜鱼汤的首选。" },
            new FishTemplate("暗河黄腊丁", 22, 13, 8, FishRarity.Rare, 1.0, 5.5, spawnWeight: 90, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Shallow, Description = "地下暗河特产的稀有鱼类，拥有特殊的斑纹，极受老练钓手的欢迎。" },
            new FishTemplate("夜行黑棘鲈", 22, 13, 8, FishRarity.Rare, 1.2, 7.0, spawnWeight: 100, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Middle, Description = "生活在地下暗河水流中的稀有鲈鱼，背鳍锐利，肉质肥嫩鲜美。" },
            new FishTemplate("五彩荧光大虾", 22, 13, 8, FishRarity.Rare, 0.6, 3.5, spawnWeight: 80, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Shallow, Description = "生活在地下暗河浅水区的稀有小虾，外壳坚硬，肉质爽脆，极其适合作为猫咪的点心。" },
            new FishTemplate("旧发条鱼", 22, 13, 8, FishRarity.Rare, 1.0, 5.0, spawnWeight: 70, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Middle, Description = "地下暗河特产的稀有鱼类，拥有特殊的斑纹，极受老练钓手的欢迎。" },
            new FishTemplate("霁光玻璃鱼", 22, 13, 8, FishRarity.Rare, 0.9, 4.5, spawnWeight: 88, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Middle, Description = "地下暗河特产的稀有鱼类，拥有特殊的斑纹，极受老练钓手的欢迎。" },
            new FishTemplate("引水五彩鲑", 35, 19, 12, FishRarity.Epic, 2.0, 10.0, spawnWeight: 100, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Middle, Description = "极其罕见的地下暗河史诗级大鱼，捕食习惯独特，拉竿手感异常沉重。" },
            new FishTemplate("地底粉红鲵", 35, 19, 12, FishRarity.Epic, 2.5, 12.0, spawnWeight: 95, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep, Description = "极其罕见的地下暗河史诗级大鱼，捕食习惯独特，拉竿手感异常沉重。" },
            new FishTemplate("七彩霓虹鲷", 35, 19, 12, FishRarity.Epic, 1.8, 9.5, spawnWeight: 92, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Middle, Description = "极其罕见的地下暗河史诗级大鱼，捕食习惯独特，拉竿手感异常沉重。" },
            new FishTemplate("暗河金丝鲃", 50, 27, 17, FishRarity.Legendary, 2.5, 12.0, spawnWeight: 100, wariness: 0.75, power: 0.82) { PreferredDepth = WaterDepth.Middle, Description = "地下暗河的领主级传说鱼，体形硕大，常掀起惊涛巨浪，是无数钓手追寻的目标。" },
            new FishTemplate("异变·“白化巨螈”", 72, 38, 25, FishRarity.Legendary, 4.5, 20.0, spawnWeight: 120, wariness: 0.88, power: 0.94) { PreferredDepth = WaterDepth.Middle, TargetLureRecipeId = "地下暗河", Description = "只存在于古老传说中的lure_albino_salamander神话神兽，受神秘饵料吸引而来，拥有不可思议的光泽与灵性。" },
        ]);
        spots["地下暗河"] = _地下暗河;

        // ── 深水海湾 Lv18 · ×1.55 · Deep ──
        var _深水海湾 = new FishingSpot("深水海湾")
        {
            FishingTime = 2,
            RequiredLevel = 18,
            PriceMultiplier = 1.55,
            PrimaryDepth = WaterDepth.Deep,
            Description = "地壳裂谷暗涌 · 高压深层 · 热液喷口矿渣",
            FishRarityTable = new()
            {
                { FishRarity.Common, 48 },
                { FishRarity.Rare, 30 },
                { FishRarity.Epic, 16 },
                { FishRarity.Legendary, 6 }
            }
        };
        _深水海湾.FishTable.AddRange([
            new FishTemplate("岩缝爬岩鱼", 14, 9, 5, FishRarity.Common, 0.5, 2.5, spawnWeight: 48, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Deep, Description = "生活在深水海湾深海的常见鱼类，口感普通，深受新猫咪的喜爱。" },
            new FishTemplate("深渊火山虾", 14, 9, 5, FishRarity.Common, 0.4, 2.0, spawnWeight: 52, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Deep, Description = "生活在深水海湾深海区的普通小虾，外壳坚硬，肉质爽脆，极其适合作为猫咪的点心。" },
            new FishTemplate("热液口磷虾", 14, 9, 5, FishRarity.Common, 0.3, 1.5, spawnWeight: 50, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Deep, Description = "生活在深水海湾深海区的普通小虾，外壳坚硬，肉质爽脆，极其适合作为猫咪的点心。" },
            new FishTemplate("裂隙盲鲫", 14, 9, 5, FishRarity.Common, 0.55, 3.0, spawnWeight: 46, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Middle, Description = "深水海湾常见的普通鲫鱼，营养丰富，是给猫咪做鲜鱼汤的首选。" },
            new FishTemplate("深水海鳗苗", 14, 9, 5, FishRarity.Common, 0.45, 2.2, spawnWeight: 44, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Deep, Description = "栖息在深水海湾暗处的普通鳗鱼，身体修长，游动姿态宛如游蛇。" },
            new FishTemplate("深海石九公", 22, 13, 8, FishRarity.Rare, 1.2, 6.0, spawnWeight: 86, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Deep, Description = "深水海湾特产的稀有鱼类，拥有特殊的斑纹，极受老练钓手的欢迎。" },
            new FishTemplate("蓝枪鱼", 22, 13, 8, FishRarity.Rare, 1.5, 8.5, spawnWeight: 90, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Deep, Description = "深水海湾特产的稀有鱼类，拥有特殊的斑纹，极受老练钓手的欢迎。" },
            new FishTemplate("裂谷无眼鲶", 22, 13, 8, FishRarity.Rare, 1.1, 5.5, spawnWeight: 82, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Deep, Description = "深水海湾特产的稀有鱼类，拥有特殊的斑纹，极受老练钓手的欢迎。" },
            new FishTemplate("热液大口黑鱼", 35, 19, 12, FishRarity.Epic, 2.4, 11.0, spawnWeight: 95, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep, Description = "极其罕见的深水海湾史诗级大鱼，捕食习惯独特，拉竿手感异常沉重。" },
            new FishTemplate("白玉长寿鳗", 35, 19, 12, FishRarity.Epic, 2.0, 10.0, spawnWeight: 92, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep, Description = "栖息在深水海湾暗处的史诗鳗鱼，身体修长，游动姿态宛如游蛇。" },
            new FishTemplate("金目鲷", 35, 19, 12, FishRarity.Epic, 2.6, 12.5, spawnWeight: 88, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep, Description = "极其罕见的深水海湾史诗级大鱼，捕食习惯独特，拉竿手感异常沉重。" },
            new FishTemplate("深湾老船长鳕鱼", 50, 27, 17, FishRarity.Legendary, 3.0, 14.0, spawnWeight: 100, wariness: 0.75, power: 0.82) { PreferredDepth = WaterDepth.Deep, Description = "深水海湾的领主级传说鱼，体形硕大，常掀起惊涛巨浪，是无数钓手追寻的目标。" },
            new FishTemplate("异变·“裂谷飞蝠”", 72, 38, 25, FishRarity.Legendary, 4.8, 21.0, spawnWeight: 120, wariness: 0.88, power: 0.94) { PreferredDepth = WaterDepth.Deep, TargetLureRecipeId = "深水海湾", Description = "只存在于古老传说中的lure_mutant_ray神话神兽，受神秘饵料吸引而来，拥有不可思议的光泽与灵性。" },
        ]);
        spots["深水海湾"] = _深水海湾;

        // ── 极光冰湾 Lv32 · ×1.8 · Deep ──
        var _极光冰湾 = new FishingSpot("极光冰湾")
        {
            FishingTime = 2,
            RequiredLevel = 32,
            PriceMultiplier = 1.8,
            PrimaryDepth = WaterDepth.Deep,
            Description = "极光环冰湾 · 寒渊深层 · 不融极地冰晶",
            FishRarityTable = new()
            {
                { FishRarity.Common, 42 },
                { FishRarity.Rare, 30 },
                { FishRarity.Epic, 20 },
                { FishRarity.Legendary, 8 }
            }
        };
        _极光冰湾.FishTable.AddRange([
            new FishTemplate("破冰雪鳞鲫", 14, 9, 5, FishRarity.Common, 0.6, 3.5, spawnWeight: 50, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Shallow, Description = "极光冰湾常见的普通鲫鱼，营养丰富，是给猫咪做鲜鱼汤的首选。" },
            new FishTemplate("极地白虾", 14, 9, 5, FishRarity.Common, 0.5, 2.5, spawnWeight: 55, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Shallow, Description = "生活在极光冰湾浅水区的普通小虾，外壳坚硬，肉质爽脆，极其适合作为猫咪的点心。" },
            new FishTemplate("冰吻沙丁鱼", 14, 9, 5, FishRarity.Common, 0.4, 2.2, spawnWeight: 52, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Shallow, Description = "生活在极光冰湾浅水的常见鱼类，口感普通，深受新猫咪的喜爱。" },
            new FishTemplate("霜斑鲱鱼", 14, 9, 5, FishRarity.Common, 0.35, 1.8, spawnWeight: 48, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Middle, Description = "生活在极光冰湾中层的常见鱼类，口感普通，深受新猫咪的喜爱。" },
            new FishTemplate("透明冰晶鱼", 22, 13, 8, FishRarity.Rare, 1.2, 6.0, spawnWeight: 100, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Deep, Description = "极光冰湾特产的稀有鱼类，拥有特殊的斑纹，极受老练钓手的欢迎。" },
            new FishTemplate("北极王鲑", 22, 13, 8, FishRarity.Rare, 1.5, 8.0, spawnWeight: 95, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Middle, Description = "极光冰湾特产的稀有鱼类，拥有特殊的斑纹，极受老练钓手的欢迎。" },
            new FishTemplate("五彩极光鳟", 22, 13, 8, FishRarity.Rare, 1.3, 7.0, spawnWeight: 88, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Middle, Description = "极光冰湾特产的稀有鱼类，拥有特殊的斑纹，极受老练钓手的欢迎。" },
            new FishTemplate("霜纹白鲂", 22, 13, 8, FishRarity.Rare, 1.0, 5.5, spawnWeight: 82, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Shallow, Description = "极光冰湾特产的稀有鱼类，拥有特殊的斑纹，极受老练钓手的欢迎。" },
            new FishTemplate("垃圾金属", 22, 13, 8, FishRarity.Rare, 1.2, 6.0, spawnWeight: 70, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Deep, Description = "极光冰湾特产的稀有鱼类，拥有特殊的斑纹，极受老练钓手的欢迎。" },
            new FishTemplate("冰川蛇鳕", 35, 19, 12, FishRarity.Epic, 1.8, 10.0, spawnWeight: 100, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep, Description = "极其罕见的极光冰湾史诗级大鱼，捕食习惯独特，拉竿手感异常沉重。" },
            new FishTemplate("北极重水鲈", 35, 19, 12, FishRarity.Epic, 2.5, 14.0, spawnWeight: 100, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep, Description = "生活在极光冰湾水流中的史诗鲈鱼，背鳍锐利，肉质肥嫩鲜美。" },
            new FishTemplate("白化冰鳕", 35, 19, 12, FishRarity.Epic, 2.0, 11.0, spawnWeight: 90, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep, Description = "极其罕见的极光冰湾史诗级大鱼，捕食习惯独特，拉竿手感异常沉重。" },
            new FishTemplate("深渊巨口宽咽鱼", 35, 19, 12, FishRarity.Epic, 2.2, 12.0, spawnWeight: 93, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep, Description = "极其罕见的极光冰湾史诗级大鱼，捕食习惯独特，拉竿手感异常沉重。" },
            new FishTemplate("极光冰川巨鳎", 50, 27, 17, FishRarity.Legendary, 3.0, 15.0, spawnWeight: 100, wariness: 0.75, power: 0.82) { PreferredDepth = WaterDepth.Deep, Description = "极光冰湾的领主级传说鱼，体形硕大，常掀起惊涛巨浪，是无数钓手追寻的目标。" },
            new FishTemplate("神话·“极光霜龙”", 72, 38, 25, FishRarity.Legendary, 6.0, 25.0, spawnWeight: 120, wariness: 0.88, power: 0.94) { PreferredDepth = WaterDepth.Deep, TargetLureRecipeId = "极光冰湾", Description = "只存在于古老传说中的lure_aurora_crystal神话神兽，受神秘饵料吸引而来，拥有不可思议的光泽与灵性。" },
            new FishTemplate("归潮蝠鲼", 35, 19, 12, FishRarity.Epic, 2.4, 12.0, spawnWeight: 30, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep, Description = "生活在极光冰湾的史诗鳐鱼，身形如扁平飞翼，在水层中优雅滑翔。" },
        ]);
        spots["极光冰湾"] = _极光冰湾;

        // ── 沉船墓场 Lv32 · ×2.0 · Deep ──
        var _沉船墓场 = new FishingSpot("沉船墓场")
        {
            FishingTime = 1,
            RequiredLevel = 32,
            PriceMultiplier = 2.0,
            PrimaryDepth = WaterDepth.Deep,
            Description = "锈蚀沉船群 · 亡魂巡游 · 百年沉船铁皮",
            FishRarityTable = new()
            {
                { FishRarity.Common, 40 },
                { FishRarity.Rare, 32 },
                { FishRarity.Epic, 20 },
                { FishRarity.Legendary, 8 }
            }
        };
        _沉船墓场.FishTable.AddRange([
            new FishTemplate("沉船缝沙丁", 14, 9, 5, FishRarity.Common, 0.3, 1.5, spawnWeight: 46, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Deep, Description = "生活在沉船墓场深海的常见鱼类，口感普通，深受新猫咪的喜爱。" },
            new FishTemplate("铁皮锈斑虾", 14, 9, 5, FishRarity.Common, 0.4, 2.0, spawnWeight: 50, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Deep, Description = "生活在沉船墓场深海区的普通小虾，外壳坚硬，肉质爽脆，极其适合作为猫咪的点心。" },
            new FishTemplate("幽灵发光浮游", 14, 9, 5, FishRarity.Common, 0.35, 1.8, spawnWeight: 48, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Deep, Description = "生活在沉船墓场深海的常见鱼类，口感普通，深受新猫咪的喜爱。" },
            new FishTemplate("沉船黑斑鳕", 14, 9, 5, FishRarity.Common, 0.45, 2.5, spawnWeight: 44, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Deep, Description = "生活在沉船墓场深海的常见鱼类，口感普通，深受新猫咪的喜爱。" },
            new FishTemplate("锈斑扁鲫", 22, 13, 8, FishRarity.Rare, 0.9, 4.5, spawnWeight: 84, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Middle, Description = "沉船墓场常见的稀有鲫鱼，营养丰富，是给猫咪做鲜鱼汤的首选。" },
            new FishTemplate("沉船黑电鳗", 22, 13, 8, FishRarity.Rare, 1.4, 8.0, spawnWeight: 88, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Deep, Description = "栖息在沉船墓场暗处的稀有鳗鱼，身体修长，游动姿态宛如游蛇。" },
            new FishTemplate("黑火透光乌贼", 22, 13, 8, FishRarity.Rare, 1.0, 6.0, spawnWeight: 80, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Deep, Description = "沉船墓场的稀有软体动物，体型柔软，能喷射荧光墨汁逃避掠食者。" },
            new FishTemplate("暗流刺盖鱼", 22, 13, 8, FishRarity.Rare, 2.3, 14.0, spawnWeight: 95, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Deep, Description = "沉船墓场特产的稀有鱼类，拥有特殊的斑纹，极受老练钓手的欢迎。" },
            new FishTemplate("深海皱鳃鲨", 35, 19, 12, FishRarity.Epic, 2.8, 15.0, spawnWeight: 100, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep, Description = "出没于沉船墓场的史诗强悍鲨鱼，处于食物链顶端，体型庞大，充满攻击性。" },
            new FishTemplate("墓场带鱼王", 35, 19, 12, FishRarity.Epic, 2.5, 13.0, spawnWeight: 92, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep, Description = "极其罕见的沉船墓场史诗级大鱼，捕食习惯独特，拉竿手感异常沉重。" },
            new FishTemplate("百年老船壳龟", 35, 19, 12, FishRarity.Epic, 3.0, 18.0, spawnWeight: 88, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Shallow, Description = "极其罕见的沉船墓场史诗级大鱼，捕食习惯独特，拉竿手感异常沉重。" },
            new FishTemplate("沉船幽灵鳕", 50, 27, 17, FishRarity.Legendary, 3.2, 16.0, spawnWeight: 100, wariness: 0.75, power: 0.82) { PreferredDepth = WaterDepth.Deep, Description = "沉船墓场的领主级传说鱼，体形硕大，常掀起惊涛巨浪，是无数钓手追寻的目标。" },
            new FishTemplate("神话·“沉船亡魂”", 72, 38, 25, FishRarity.Legendary, 5.5, 23.0, spawnWeight: 120, wariness: 0.88, power: 0.94) { PreferredDepth = WaterDepth.Deep, TargetLureRecipeId = "沉船墓场", Description = "只存在于古老传说中的lure_wreck_soul神话神兽，受神秘饵料吸引而来，拥有不可思议的光泽与灵性。" },
        ]);
        spots["沉船墓场"] = _沉船墓场;

        // ── 珊瑚暗流 Lv32 · ×1.95 · Deep ──
        var _珊瑚暗流 = new FishingSpot("珊瑚暗流")
        {
            FishingTime = 2,
            RequiredLevel = 32,
            PriceMultiplier = 1.95,
            PrimaryDepth = WaterDepth.Deep,
            Description = "珊瑚礁暗流带 · 隐蔽深层 · 红珊瑚碎屑",
            FishRarityTable = new()
            {
                { FishRarity.Common, 40 },
                { FishRarity.Rare, 32 },
                { FishRarity.Epic, 20 },
                { FishRarity.Legendary, 8 }
            }
        };
        _珊瑚暗流.FishTable.AddRange([
            new FishTemplate("红海葵小丑鱼", 14, 9, 5, FishRarity.Common, 0.5, 2.5, spawnWeight: 55, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Shallow, Description = "生活在珊瑚暗流浅水的常见鱼类，口感普通，深受新猫咪的喜爱。" },
            new FishTemplate("珊瑚缝雀尾虾", 14, 9, 5, FishRarity.Common, 0.3, 1.5, spawnWeight: 50, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Middle, Description = "生活在珊瑚暗流中层区的普通小虾，外壳坚硬，肉质爽脆，极其适合作为猫咪的点心。" },
            new FishTemplate("五彩玻璃雀鲷", 14, 9, 5, FishRarity.Common, 0.4, 2.0, spawnWeight: 48, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Middle, Description = "生活在珊瑚暗流中层的常见鱼类，口感普通，深受新猫咪的喜爱。" },
            new FishTemplate("红点玻璃墨鱼", 14, 9, 5, FishRarity.Common, 0.45, 2.2, spawnWeight: 46, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Deep, Description = "生活在珊瑚暗流深海的常见鱼类，口感普通，深受新猫咪的喜爱。" },
            new FishTemplate("珊瑚沙丁", 14, 9, 5, FishRarity.Common, 0.28, 1.4, spawnWeight: 44, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Shallow, Description = "生活在珊瑚暗流浅水的常见鱼类，口感普通，深受新猫咪的喜爱。" },
            new FishTemplate("红眉斑石斑", 22, 13, 8, FishRarity.Rare, 1.1, 6.0, spawnWeight: 88, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Middle, Description = "珊瑚暗流特产的稀有鱼类，拥有特殊的斑纹，极受老练钓手的欢迎。" },
            new FishTemplate("烈焰红仙子", 22, 13, 8, FishRarity.Rare, 1.1, 6.5, spawnWeight: 82, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Middle, Description = "珊瑚暗流特产的稀有鱼类，拥有特殊的斑纹，极受老练钓手的欢迎。" },
            new FishTemplate("珊瑚白星裸胸鳝", 22, 13, 8, FishRarity.Rare, 1.5, 9.0, spawnWeight: 90, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Deep, Description = "珊瑚暗流特产的稀有鱼类，拥有特殊的斑纹，极受老练钓手的欢迎。" },
            new FishTemplate("红星狼鲈", 35, 19, 12, FishRarity.Epic, 2.0, 11.0, spawnWeight: 95, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep, Description = "生活在珊瑚暗流水流中的史诗鲈鱼，背鳍锐利，肉质肥嫩鲜美。" },
            new FishTemplate("玳瑁巨海龟", 35, 19, 12, FishRarity.Epic, 3.0, 18.0, spawnWeight: 88, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Shallow, Description = "极其罕见的珊瑚暗流史诗级大鱼，捕食习惯独特，拉竿手感异常沉重。" },
            new FishTemplate("红花金枪鱿", 35, 19, 12, FishRarity.Epic, 2.6, 13.0, spawnWeight: 92, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep, Description = "珊瑚暗流的史诗软体动物，体型柔软，能喷射荧光墨汁逃避掠食者。" },
            new FishTemplate("红珊瑚金眼鲷", 50, 27, 17, FishRarity.Legendary, 2.8, 14.0, spawnWeight: 100, wariness: 0.75, power: 0.82) { PreferredDepth = WaterDepth.Deep, Description = "珊瑚暗流的领主级传说鱼，体形硕大，常掀起惊涛巨浪，是无数钓手追寻的目标。" },
            new FishTemplate("神话·“珊瑚心海”", 72, 38, 25, FishRarity.Legendary, 5.2, 22.0, spawnWeight: 118, wariness: 0.88, power: 0.94) { PreferredDepth = WaterDepth.Deep, TargetLureRecipeId = "珊瑚暗流", Description = "只存在于古老传说中的lure_coral_heart神话神兽，受神秘饵料吸引而来，拥有不可思议的光泽与灵性。" },
        ]);
        spots["珊瑚暗流"] = _珊瑚暗流;

        // ── 远礁外海 Lv45 · ×2.2 · Deep ──
        var _远礁外海 = new FishingSpot("远礁外海")
        {
            FishingTime = 1,
            RequiredLevel = 45,
            PriceMultiplier = 2.2,
            PrimaryDepth = WaterDepth.Deep,
            Description = "远礁外海开放水域 · 高周转 · 落星陨铁晶核",
            FishRarityTable = new()
            {
                { FishRarity.Common, 35 },
                { FishRarity.Rare, 32 },
                { FishRarity.Epic, 22 },
                { FishRarity.Legendary, 11 }
            }
        };
        _远礁外海.FishTable.AddRange([
            new FishTemplate("礁盘黄鸡鱼", 14, 9, 5, FishRarity.Common, 1.0, 5.0, spawnWeight: 45, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Middle, Description = "生活在远礁外海中层的常见鱼类，口感普通，深受新猫咪的喜爱。" },
            new FishTemplate("蓝背沙丁鱼", 14, 9, 5, FishRarity.Common, 0.3, 1.5, spawnWeight: 50, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Shallow, Description = "生活在远礁外海浅水的常见鱼类，口感普通，深受新猫咪的喜爱。" },
            new FishTemplate("外海浮游磷虾", 14, 9, 5, FishRarity.Common, 0.35, 1.8, spawnWeight: 48, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Deep, Description = "生活在远礁外海深海区的普通小虾，外壳坚硬，肉质爽脆，极其适合作为猫咪的点心。" },
            new FishTemplate("礁影石九公", 14, 9, 5, FishRarity.Common, 0.4, 2.2, spawnWeight: 44, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Deep, Description = "生活在远礁外海深海的常见鱼类，口感普通，深受新猫咪的喜爱。" },
            new FishTemplate("深水海鳝", 22, 13, 8, FishRarity.Rare, 1.5, 9.0, spawnWeight: 100, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Deep, Description = "远礁外海特产的稀有鱼类，拥有特殊的斑纹，极受老练钓手的欢迎。" },
            new FishTemplate("蓝鳍金枪鱼", 22, 13, 8, FishRarity.Rare, 2.0, 12.0, spawnWeight: 95, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Deep, Description = "远礁外海特产的稀有鱼类，拥有特殊的斑纹，极受老练钓手的欢迎。" },
            new FishTemplate("大马鲛鱼", 22, 13, 8, FishRarity.Rare, 1.4, 8.0, spawnWeight: 90, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Deep, Description = "远礁外海特产的稀有鱼类，拥有特殊的斑纹，极受老练钓手的欢迎。" },
            new FishTemplate("飞翼蝠鲼", 35, 19, 12, FishRarity.Epic, 2.5, 16.0, spawnWeight: 100, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep, Description = "生活在远礁外海的史诗鳐鱼，身形如扁平飞翼，在水层中优雅滑翔。" },
            new FishTemplate("黑皮旗鱼", 35, 19, 12, FishRarity.Epic, 2.3, 14.0, spawnWeight: 92, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep, Description = "极其罕见的远礁外海史诗级大鱼，捕食习惯独特，拉竿手感异常沉重。" },
            new FishTemplate("巨型红鱿鱼", 35, 19, 12, FishRarity.Epic, 2.8, 15.0, spawnWeight: 88, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep, Description = "远礁外海的史诗软体动物，体型柔软，能喷射荧光墨汁逃避掠食者。" },
            new FishTemplate("大洋金鳞鲷", 50, 27, 17, FishRarity.Legendary, 3.0, 18.0, spawnWeight: 100, wariness: 0.75, power: 0.82) { PreferredDepth = WaterDepth.Deep, Description = "远礁外海的领主级传说鱼，体形硕大，常掀起惊涛巨浪，是无数钓手追寻的目标。" },
            new FishTemplate("大白鲨", 50, 27, 17, FishRarity.Legendary, 4.0, 25.0, spawnWeight: 100, wariness: 0.75, power: 0.82) { PreferredDepth = WaterDepth.Deep, Description = "出没于远礁外海的传说强悍鲨鱼，处于食物链顶端，体型庞大，充满攻击性。" },
            new FishTemplate("神话·“远海沧龙”", 72, 38, 25, FishRarity.Legendary, 6.5, 28.0, spawnWeight: 120, wariness: 0.88, power: 0.94) { PreferredDepth = WaterDepth.Deep, TargetLureRecipeId = "远礁外海", Description = "只存在于古老传说中的lure_reef_leviathan神话神兽，受神秘饵料吸引而来，拥有不可思议的光泽与灵性。" },
            new FishTemplate("神话·“金鳞海皇”", 72, 38, 25, FishRarity.Legendary, 5.5, 24.0, spawnWeight: 115, wariness: 0.88, power: 0.94) { PreferredDepth = WaterDepth.Deep, TargetLureRecipeId = "远礁外海", Description = "只存在于古老传说中的lure_sea_emperor神话神兽，受神秘饵料吸引而来，拥有不可思议的光泽与灵性。" },
            new FishTemplate("跨洋银裸胸鳝", 22, 13, 8, FishRarity.Rare, 1.6, 9.5, spawnWeight: 35, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Deep, Description = "远礁外海特产的稀有鱼类，拥有特殊的斑纹，极受老练钓手的欢迎。" },
            new FishTemplate("归潮蝠鲼", 35, 19, 12, FishRarity.Epic, 2.4, 12.0, spawnWeight: 30, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep, Description = "生活在远礁外海的史诗鳐鱼，身形如扁平飞翼，在水层中优雅滑翔。" },
        ]);
        spots["远礁外海"] = _远礁外海;

        // ── 深渊回廊 Lv45 · ×2.5 · Deep ──
        var _深渊回廊 = new FishingSpot("深渊回廊")
        {
            FishingTime = 1,
            RequiredLevel = 45,
            PriceMultiplier = 2.5,
            PrimaryDepth = WaterDepth.Deep,
            Description = "海底裂隙回廊 · 凝胶矿脉 · 深渊巨兽粘液",
            FishRarityTable = new()
            {
                { FishRarity.Common, 32 },
                { FishRarity.Rare, 34 },
                { FishRarity.Epic, 24 },
                { FishRarity.Legendary, 10 }
            }
        };
        _深渊回廊.FishTable.AddRange([
            new FishTemplate("裂隙小鳚", 14, 9, 5, FishRarity.Common, 0.4, 2.2, spawnWeight: 44, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Deep, Description = "生活在深渊回廊深海的常见鱼类，口感普通，深受新猫咪的喜爱。" },
            new FishTemplate("深渊透明小介虫", 14, 9, 5, FishRarity.Common, 0.35, 1.8, spawnWeight: 50, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Deep, Description = "生活在深渊回廊深海的常见鱼类，口感普通，深受新猫咪的喜爱。" },
            new FishTemplate("透明凝胶水母", 14, 9, 5, FishRarity.Common, 0.3, 1.5, spawnWeight: 48, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Deep, Description = "生活在深渊回廊深海的常见鱼类，口感普通，深受新猫咪的喜爱。" },
            new FishTemplate("深渊琵琶鱼", 14, 9, 5, FishRarity.Common, 0.5, 2.8, spawnWeight: 46, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Middle, Description = "生活在深渊回廊深渊处的普通安康鱼，头顶挂有发光灯笼，长相奇特。" },
            new FishTemplate("黑首阿氏鲈", 22, 13, 8, FishRarity.Rare, 1.3, 7.0, spawnWeight: 86, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Deep, Description = "生活在深渊回廊水流中的稀有鲈鱼，背鳍锐利，肉质肥嫩鲜美。" },
            new FishTemplate("回廊电箭鳗", 22, 13, 8, FishRarity.Rare, 1.6, 9.5, spawnWeight: 90, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Deep, Description = "栖息在深渊回廊暗处的稀有鳗鱼，身体修长，游动姿态宛如游蛇。" },
            new FishTemplate("凝胶玻璃鱿", 22, 13, 8, FishRarity.Rare, 1.2, 7.5, spawnWeight: 84, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Deep, Description = "深渊回廊的稀有软体动物，体型柔软，能喷射荧光墨汁逃避掠食者。" },
            new FishTemplate("深海巨齿鱼", 35, 19, 12, FishRarity.Epic, 2.6, 13.0, spawnWeight: 95, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep, Description = "极其罕见的深渊回廊史诗级大鱼，捕食习惯独特，拉竿手感异常沉重。" },
            new FishTemplate("黑鬼安康鱼", 35, 19, 12, FishRarity.Epic, 3.0, 14.0, spawnWeight: 92, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep, Description = "生活在深渊回廊深渊处的史诗安康鱼，头顶挂有发光灯笼，长相奇特。" },
            new FishTemplate("回廊蝠鳐", 35, 19, 12, FishRarity.Epic, 2.8, 15.0, spawnWeight: 88, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep, Description = "生活在深渊回廊的史诗鳐鱼，身形如扁平飞翼，在水层中优雅滑翔。" },
            new FishTemplate("格陵兰睡鲨", 50, 27, 17, FishRarity.Legendary, 3.5, 20.0, spawnWeight: 100, wariness: 0.75, power: 0.82) { PreferredDepth = WaterDepth.Deep, Description = "出没于深渊回廊的传说强悍鲨鱼，处于食物链顶端，体型庞大，充满攻击性。" },
            new FishTemplate("神话·“深渊巡礼者”", 72, 38, 25, FishRarity.Legendary, 6.0, 26.0, spawnWeight: 120, wariness: 0.88, power: 0.94) { PreferredDepth = WaterDepth.Deep, TargetLureRecipeId = "深渊回廊", Description = "只存在于古老传说中的lure_abyss_walker神话神兽，受神秘饵料吸引而来，拥有不可思议的光泽与灵性。" },
            new FishTemplate("跨洋银裸胸鳝", 22, 13, 8, FishRarity.Rare, 1.6, 9.5, spawnWeight: 35, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Deep, Description = "深渊回廊特产的稀有鱼类，拥有特殊的斑纹，极受老练钓手的欢迎。" },
            new FishTemplate("星尘巡浪鱼", 22, 13, 8, FishRarity.Rare, 1.2, 7.0, spawnWeight: 28, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Deep, Description = "深渊回廊特产的稀有鱼类，拥有特殊的斑纹，极受老练钓手的欢迎。" },
        ]);
        spots["深渊回廊"] = _深渊回廊;

        // ── 星潮海沟 Lv45 · ×2.6 · Deep ──
        var _星潮海沟 = new FishingSpot("星潮海沟")
        {
            FishingTime = 1,
            RequiredLevel = 45,
            PriceMultiplier = 2.6,
            PrimaryDepth = WaterDepth.Deep,
            Description = "星潮引力海沟 · 潮汐异种 · 月汐重力碎屑",
            FishRarityTable = new()
            {
                { FishRarity.Common, 30 },
                { FishRarity.Rare, 34 },
                { FishRarity.Epic, 26 },
                { FishRarity.Legendary, 10 }
            }
        };
        _星潮海沟.FishTable.AddRange([
            new FishTemplate("潮汐玻璃鲱", 14, 9, 5, FishRarity.Common, 0.3, 1.5, spawnWeight: 46, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Deep, Description = "生活在星潮海沟深海的常见鱼类，口感普通，深受新猫咪的喜爱。" },
            new FishTemplate("潮汐玻璃虾", 14, 9, 5, FishRarity.Common, 0.35, 1.8, spawnWeight: 50, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Deep, Description = "生活在星潮海沟深海区的普通小虾，外壳坚硬，肉质爽脆，极其适合作为猫咪的点心。" },
            new FishTemplate("星光浮游", 14, 9, 5, FishRarity.Common, 0.28, 1.4, spawnWeight: 48, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Deep, Description = "生活在星潮海沟深海的常见鱼类，口感普通，深受新猫咪的喜爱。" },
            new FishTemplate("海沟扁头鱼", 14, 9, 5, FishRarity.Common, 0.45, 2.5, spawnWeight: 44, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Middle, Description = "生活在星潮海沟中层的常见鱼类，口感普通，深受新猫咪的喜爱。" },
            new FishTemplate("星点刺盖鲈", 22, 13, 8, FishRarity.Rare, 1.4, 7.5, spawnWeight: 88, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Deep, Description = "生活在星潮海沟水流中的稀有鲈鱼，背鳍锐利，肉质肥嫩鲜美。" },
            new FishTemplate("星海大带鱼", 22, 13, 8, FishRarity.Rare, 1.8, 10.0, spawnWeight: 92, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Deep, Description = "星潮海沟特产的稀有鱼类，拥有特殊的斑纹，极受老练钓手的欢迎。" },
            new FishTemplate("星斑裸胸鳝", 22, 13, 8, FishRarity.Rare, 1.5, 9.0, spawnWeight: 86, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Deep, Description = "星潮海沟特产的稀有鱼类，拥有特殊的斑纹，极受老练钓手的欢迎。" },
            new FishTemplate("海沟深邃巨口鱼", 35, 19, 12, FishRarity.Epic, 2.8, 14.0, spawnWeight: 95, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep, Description = "极其罕见的星潮海沟史诗级大鱼，捕食习惯独特，拉竿手感异常沉重。" },
            new FishTemplate("潮汐蝠鳐", 35, 19, 12, FishRarity.Epic, 3.0, 16.0, spawnWeight: 90, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep, Description = "生活在星潮海沟的史诗鳐鱼，身形如扁平飞翼，在水层中优雅滑翔。" },
            new FishTemplate("星潮皱鳃鲨", 35, 19, 12, FishRarity.Epic, 2.6, 13.5, spawnWeight: 88, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep, Description = "出没于星潮海沟的史诗强悍鲨鱼，处于食物链顶端，体型庞大，充满攻击性。" },
            new FishTemplate("星海巨鳞鳕", 50, 27, 17, FishRarity.Legendary, 3.8, 22.0, spawnWeight: 100, wariness: 0.75, power: 0.82) { PreferredDepth = WaterDepth.Deep, Description = "星潮海沟的领主级传说鱼，体形硕大，常掀起惊涛巨浪，是无数钓手追寻的目标。" },
            new FishTemplate("神话·“星潮巨兽”", 72, 38, 25, FishRarity.Legendary, 6.2, 27.0, spawnWeight: 120, wariness: 0.88, power: 0.94) { PreferredDepth = WaterDepth.Deep, TargetLureRecipeId = "星潮海沟", Description = "只存在于古老传说中的lure_star_tide神话神兽，受神秘饵料吸引而来，拥有不可思议的光泽与灵性。" },
            new FishTemplate("跨洋银裸胸鳝", 22, 13, 8, FishRarity.Rare, 1.6, 9.5, spawnWeight: 35, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Deep, Description = "星潮海沟特产的稀有鱼类，拥有特殊的斑纹，极受老练钓手的欢迎。" },
            new FishTemplate("归潮蝠鲼", 35, 19, 12, FishRarity.Epic, 2.4, 12.0, spawnWeight: 30, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep, Description = "生活在星潮海沟的史诗鳐鱼，身形如扁平飞翼，在水层中优雅滑翔。" },
            new FishTemplate("星尘巡浪鱼", 22, 13, 8, FishRarity.Rare, 1.2, 7.0, spawnWeight: 28, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Deep, Description = "星潮海沟特产的稀有鱼类，拥有特殊的斑纹，极受老练钓手的欢迎。" },
        ]);
        spots["星潮海沟"] = _星潮海沟;

        // ── 虚空钓域 Lv60 · ×3.0 · Deep ──
        var _虚空钓域 = new FishingSpot("虚空钓域")
        {
            FishingTime = 1,
            RequiredLevel = 60,
            PriceMultiplier = 3.0,
            PrimaryDepth = WaterDepth.Deep,
            Description = "终局虚空水域 · 全神话解锁 · 裂隙虚空丝线终极产",
            FishRarityTable = new()
            {
                { FishRarity.Common, 28 },
                { FishRarity.Rare, 30 },
                { FishRarity.Epic, 28 },
                { FishRarity.Legendary, 14 }
            }
        };
        _虚空钓域.FishTable.AddRange([
            new FishTemplate("虚影介虫", 14, 9, 5, FishRarity.Common, 0.4, 2.0, spawnWeight: 42, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Deep, Description = "生活在虚空钓域深海的常见鱼类，口感普通，深受新猫咪的喜爱。" },
            new FishTemplate("裂隙小鳕", 14, 9, 5, FishRarity.Common, 0.45, 2.5, spawnWeight: 44, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Deep, Description = "生活在虚空钓域深海的常见鱼类，口感普通，深受新猫咪的喜爱。" },
            new FishTemplate("虚无玻璃虾", 14, 9, 5, FishRarity.Common, 0.35, 1.8, spawnWeight: 48, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Deep, Description = "生活在虚空钓域深海区的普通小虾，外壳坚硬，肉质爽脆，极其适合作为猫咪的点心。" },
            new FishTemplate("虚空发光鲫", 14, 9, 5, FishRarity.Common, 0.5, 3.0, spawnWeight: 46, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Middle, Description = "虚空钓域常见的普通鲫鱼，营养丰富，是给猫咪做鲜鱼汤的首选。" },
            new FishTemplate("虚空棘鲷", 22, 13, 8, FishRarity.Rare, 1.5, 8.0, spawnWeight: 85, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Deep, Description = "虚空钓域特产的稀有鱼类，拥有特殊的斑纹，极受老练钓手的欢迎。" },
            new FishTemplate("虚空电箭鳗", 22, 13, 8, FishRarity.Rare, 1.8, 10.5, spawnWeight: 90, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Deep, Description = "栖息在虚空钓域暗处的稀有鳗鱼，身体修长，游动姿态宛如游蛇。" },
            new FishTemplate("虚幻透明鱿", 22, 13, 8, FishRarity.Rare, 1.3, 8.0, spawnWeight: 82, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Deep, Description = "虚空钓域的稀有软体动物，体型柔软，能喷射荧光墨汁逃避掠食者。" },
            new FishTemplate("虚空巨口鱼", 35, 19, 12, FishRarity.Epic, 3.0, 15.0, spawnWeight: 95, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep, Description = "极其罕见的虚空钓域史诗级大鱼，捕食习惯独特，拉竿手感异常沉重。" },
            new FishTemplate("虚空飞蝠", 35, 19, 12, FishRarity.Epic, 3.2, 17.0, spawnWeight: 92, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep, Description = "极其罕见的虚空钓域史诗级大鱼，捕食习惯独特，拉竿手感异常沉重。" },
            new FishTemplate("虚空幽灵鲨", 35, 19, 12, FishRarity.Epic, 2.8, 14.5, spawnWeight: 88, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep, Description = "出没于虚空钓域的史诗强悍鲨鱼，处于食物链顶端，体型庞大，充满攻击性。" },
            new FishTemplate("终焉红棘鲷", 50, 27, 17, FishRarity.Legendary, 4.5, 28.0, spawnWeight: 100, wariness: 0.75, power: 0.82) { PreferredDepth = WaterDepth.Deep, Description = "虚空钓域的领主级传说鱼，体形硕大，常掀起惊涛巨浪，是无数钓手追寻的目标。" },
            new FishTemplate("虚空巨鲸影", 50, 27, 17, FishRarity.Legendary, 5.0, 32.0, spawnWeight: 95, wariness: 0.75, power: 0.82) { PreferredDepth = WaterDepth.Deep, Description = "虚空钓域的领主级传说鱼，体形硕大，常掀起惊涛巨浪，是无数钓手追寻的目标。" },
            new FishTemplate("神话·“虚空钓主”", 72, 38, 25, FishRarity.Legendary, 7.0, 30.0, spawnWeight: 125, wariness: 0.88, power: 0.94) { PreferredDepth = WaterDepth.Deep, TargetLureRecipeId = "虚空钓域", Description = "只存在于古老传说中的lure_void_master神话神兽，受神秘饵料吸引而来，拥有不可思议的光泽与灵性。" },
            new FishTemplate("神话·“终焉鲸歌”", 72, 38, 25, FishRarity.Legendary, 6.8, 29.0, spawnWeight: 122, wariness: 0.88, power: 0.94) { PreferredDepth = WaterDepth.Deep, TargetLureRecipeId = "虚空钓域", Description = "只存在于古老传说中的lure_void_whale神话神兽，受神秘饵料吸引而来，拥有不可思议的光泽与灵性。" },
            new FishTemplate("星尘巡浪鱼", 22, 13, 8, FishRarity.Rare, 1.2, 7.0, spawnWeight: 28, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Deep, Description = "虚空钓域特产的稀有鱼类，拥有特殊的斑纹，极受老练钓手的欢迎。" },
        ]);
        spots["虚空钓域"] = _虚空钓域;

    }

    private static IReadOnlyDictionary<string, string[]> PreviewFishMap => new Dictionary<string, string[]>
    {
        ["镇外溪流"] = ["溪边小白条", "野花翅子(虹鳟)", "金背鲤仙"],
        ["废弃鱼塘"] = ["烂泥塘鲫鱼", "烂泥塘大青鱼", "塘主·“独眼老草鱼”"],
        ["近海礁石"] = ["荧光墨鱼", "大灯笼安康鱼", "斑斓大石斑"],
        ["芦苇湿地"] = ["野性湿地鲈", "泥沼黄斑大鲶", "湿地老青鲩"],
        ["地下暗河"] = ["暗河黄腊丁", "引水五彩鲑", "暗河金丝鲃"],
        ["深水海湾"] = ["蓝枪鱼", "热液大口黑鱼", "深湾老船长鳕鱼"],
        ["极光冰湾"] = ["透明冰晶鱼", "冰川蛇鳕", "极光冰川巨鳎"],
        ["沉船墓场"] = ["暗流刺盖鱼", "深海皱鳃鲨", "沉船幽灵鳕"],
        ["珊瑚暗流"] = ["红眉斑石斑", "红星狼鲈", "红珊瑚金眼鲷"],
        ["远礁外海"] = ["深水海鳝", "大洋金鳞鲷", "大白鲨"],
        ["深渊回廊"] = ["回廊电箭鳗", "黑鬼安康鱼", "格陵兰睡鲨"],
        ["星潮海沟"] = ["星海大带鱼", "潮汐蝠鳐", "星海巨鳞鳕"],
        ["虚空钓域"] = ["虚空巨口鱼", "终焉红棘鲷", "神话·“虚空钓主”"],
    };
}
