// <auto-generated by tools/gen_fishing_spots.py — do not edit by hand>
namespace CyberPetApp.Models;

public static partial class FishingSpotCatalog
{
    private static void BuildAllSpots(Dictionary<string, FishingSpot> spots)
    {
        // ── 静溪 Lv1 · ×1.0 · Shallow ──
        var _静溪 = new FishingSpot("静溪")
        {
            FishingTime = 2,
            RequiredLevel = 1,
            PriceMultiplier = 1.0,
            PrimaryDepth = WaterDepth.Shallow,
            Description = "终端新手流域 · 浅层缓流 · 竹片与水草主产",
        };
        _静溪.FishTable.AddRange([
            new FishTemplate("野生鲫鱼", 14, 9, 5, FishRarity.Common, 0.5, 3.0, spawnWeight: 50, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Shallow },
            new FishTemplate("大口鲈鱼", 14, 9, 5, FishRarity.Common, 1.0, 5.0, spawnWeight: 45, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Shallow },
            new FishTemplate("草虾", 14, 9, 5, FishRarity.Common, 0.3, 1.5, spawnWeight: 55, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Shallow },
            new FishTemplate("溪蟹", 14, 9, 5, FishRarity.Common, 0.2, 1.0, spawnWeight: 48, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Shallow },
            new FishTemplate("柳根鱼", 14, 9, 5, FishRarity.Common, 0.4, 2.0, spawnWeight: 52, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Shallow },
            new FishTemplate("浮萍鱼", 14, 9, 5, FishRarity.Common, 0.3, 1.2, spawnWeight: 46, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Shallow },
            new FishTemplate("弹跳泥鳅", 22, 13, 8, FishRarity.Rare, 0.8, 4.0, spawnWeight: 80, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Shallow },
            new FishTemplate("彩虹鳟鱼", 22, 13, 8, FishRarity.Rare, 1.5, 6.0, spawnWeight: 100, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Middle },
            new FishTemplate("溪石鳜", 22, 13, 8, FishRarity.Rare, 1.2, 5.5, spawnWeight: 85, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Shallow },
            new FishTemplate("翠鳞银鳟", 35, 19, 12, FishRarity.Epic, 1.8, 7.5, spawnWeight: 95, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Middle },
            new FishTemplate("溪涧银龙", 35, 19, 12, FishRarity.Epic, 2.0, 8.0, spawnWeight: 100, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Middle },
            new FishTemplate("镜湖灵鲤", 35, 19, 12, FishRarity.Epic, 2.2, 9.0, spawnWeight: 90, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Shallow },
            new FishTemplate("黄金锦鲤", 50, 27, 17, FishRarity.Legendary, 2.0, 10.0, spawnWeight: 100, wariness: 0.75, power: 0.82) { PreferredDepth = WaterDepth.Shallow },
            new FishTemplate("神话·镜湖神鲤", 72, 38, 25, FishRarity.Legendary, 4.0, 18.0, spawnWeight: 120, wariness: 0.88, power: 0.94) { PreferredDepth = WaterDepth.Shallow, TargetLureRecipeId = "lure_mirror_koi" },
            new FishTemplate("神话·翠影鳗王", 72, 38, 25, FishRarity.Legendary, 3.5, 16.0, spawnWeight: 110, wariness: 0.88, power: 0.94) { PreferredDepth = WaterDepth.Middle, TargetLureRecipeId = "lure_creek_eel" },
        ]);
        spots["静溪"] = _静溪;

        // ── 浅塘 Lv1 · ×1.05 · Shallow ──
        var _浅塘 = new FishingSpot("浅塘")
        {
            FishingTime = 2,
            RequiredLevel = 1,
            PriceMultiplier = 1.05,
            PrimaryDepth = WaterDepth.Shallow,
            Description = "城郊人工浅塘 · 莲叶遮蔽 · 入门练竿",
        };
        _浅塘.FishTable.AddRange([
            new FishTemplate("浅塘鲫", 14, 9, 5, FishRarity.Common, 0.4, 2.5, spawnWeight: 52, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Shallow },
            new FishTemplate("塘畔虾", 14, 9, 5, FishRarity.Common, 0.25, 1.2, spawnWeight: 58, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Shallow },
            new FishTemplate("水莲鱼", 14, 9, 5, FishRarity.Common, 0.35, 1.8, spawnWeight: 50, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Shallow },
            new FishTemplate("泥鲫", 14, 9, 5, FishRarity.Common, 0.45, 2.2, spawnWeight: 48, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Shallow },
            new FishTemplate("浮萍鲤", 14, 9, 5, FishRarity.Common, 0.5, 2.8, spawnWeight: 46, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Shallow },
            new FishTemplate("荷影小鳅", 14, 9, 5, FishRarity.Common, 0.3, 1.5, spawnWeight: 44, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Shallow },
            new FishTemplate("浅塘鲤", 22, 13, 8, FishRarity.Rare, 0.9, 4.5, spawnWeight: 82, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Shallow },
            new FishTemplate("荷塘蟹", 22, 13, 8, FishRarity.Rare, 0.7, 3.5, spawnWeight: 78, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Shallow },
            new FishTemplate("琉璃鳞鱼", 35, 19, 12, FishRarity.Epic, 1.6, 7.0, spawnWeight: 92, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Middle },
            new FishTemplate("浅塘银鳟", 35, 19, 12, FishRarity.Epic, 1.9, 8.0, spawnWeight: 88, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Shallow },
            new FishTemplate("塘主金鲤", 50, 27, 17, FishRarity.Legendary, 2.2, 11.0, spawnWeight: 100, wariness: 0.75, power: 0.82) { PreferredDepth = WaterDepth.Shallow },
            new FishTemplate("神话·浅塘幻鳞", 72, 38, 25, FishRarity.Legendary, 3.8, 15.0, spawnWeight: 115, wariness: 0.88, power: 0.94) { PreferredDepth = WaterDepth.Shallow, TargetLureRecipeId = "lure_shallow_pond" },
        ]);
        spots["浅塘"] = _浅塘;

        // ── 雾海深渊 Lv8 · ×1.25 · Deep ──
        var _雾海深渊 = new FishingSpot("雾海深渊")
        {
            FishingTime = 2,
            RequiredLevel = 8,
            PriceMultiplier = 1.25,
            PrimaryDepth = WaterDepth.Deep,
            Description = "离岸雾墙 · 磷光深海 · 碳纤维主产",
            FishRarityTable = new()
            {
                { FishRarity.Common, 55 },
                { FishRarity.Rare, 25 },
                { FishRarity.Epic, 14 },
                { FishRarity.Legendary, 6 }
            }
        };
        _雾海深渊.FishTable.AddRange([
            new FishTemplate("雾海鲈鱼", 14, 9, 5, FishRarity.Common, 1.0, 5.0, spawnWeight: 40, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("雾海鲫鱼", 14, 9, 5, FishRarity.Common, 0.5, 3.0, spawnWeight: 60, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("沙蚕幼体", 14, 9, 5, FishRarity.Common, 0.4, 2.0, spawnWeight: 50, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Shallow },
            new FishTemplate("磷光小鱿", 14, 9, 5, FishRarity.Common, 0.5, 2.5, spawnWeight: 55, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Middle },
            new FishTemplate("雾海浮游群", 14, 9, 5, FishRarity.Common, 0.3, 1.5, spawnWeight: 48, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("幽光幼鳗", 14, 9, 5, FishRarity.Common, 0.45, 2.2, spawnWeight: 46, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("夜光乌贼", 22, 13, 8, FishRarity.Rare, 1.0, 7.0, spawnWeight: 100, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Middle },
            new FishTemplate("深渊电鳗", 22, 13, 8, FishRarity.Rare, 1.5, 9.0, spawnWeight: 90, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("银鳍枪鱼", 22, 13, 8, FishRarity.Rare, 1.3, 8.0, spawnWeight: 85, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("珊瑚焰鱼", 22, 13, 8, FishRarity.Rare, 1.1, 6.5, spawnWeight: 80, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Middle },
            new FishTemplate("幽蓝安康", 35, 19, 12, FishRarity.Epic, 3.0, 12.0, spawnWeight: 100, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("深渊鳐", 35, 19, 12, FishRarity.Epic, 2.5, 15.0, spawnWeight: 85, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("雾海巨鱿", 35, 19, 12, FishRarity.Epic, 2.8, 13.0, spawnWeight: 92, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("雾海锦鳞", 50, 27, 17, FishRarity.Legendary, 2.0, 10.0, spawnWeight: 100, wariness: 0.75, power: 0.82) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("神话·雾海古神鱿", 72, 38, 25, FishRarity.Legendary, 5.0, 22.0, spawnWeight: 120, wariness: 0.88, power: 0.94) { PreferredDepth = WaterDepth.Deep, TargetLureRecipeId = "lure_abyss_core" },
        ]);
        spots["雾海深渊"] = _雾海深渊;

        // ── 芦苇湾 Lv12 · ×1.3 · Shallow ──
        var _芦苇湾 = new FishingSpot("芦苇湾")
        {
            FishingTime = 2,
            RequiredLevel = 12,
            PriceMultiplier = 1.3,
            PrimaryDepth = WaterDepth.Shallow,
            Description = "芦苇荡浅湾 · 风噪掩蔽 · 芦苇纤维副产",
            FishRarityTable = new()
            {
                { FishRarity.Common, 52 },
                { FishRarity.Rare, 28 },
                { FishRarity.Epic, 14 },
                { FishRarity.Legendary, 6 }
            }
        };
        _芦苇湾.FishTable.AddRange([
            new FishTemplate("芦苇鲫", 14, 9, 5, FishRarity.Common, 0.5, 2.8, spawnWeight: 50, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Shallow },
            new FishTemplate("湾口虾", 14, 9, 5, FishRarity.Common, 0.3, 1.6, spawnWeight: 54, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Shallow },
            new FishTemplate("苇影小鳅", 14, 9, 5, FishRarity.Common, 0.4, 2.0, spawnWeight: 48, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Shallow },
            new FishTemplate("风纹银鲫", 14, 9, 5, FishRarity.Common, 0.55, 3.0, spawnWeight: 46, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Shallow },
            new FishTemplate("湾畔蟹", 14, 9, 5, FishRarity.Common, 0.35, 1.8, spawnWeight: 52, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Shallow },
            new FishTemplate("芦花浮鱼", 14, 9, 5, FishRarity.Common, 0.28, 1.4, spawnWeight: 44, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Middle },
            new FishTemplate("芦苇鲈", 22, 13, 8, FishRarity.Rare, 1.1, 5.5, spawnWeight: 88, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Middle },
            new FishTemplate("湾影鳜", 22, 13, 8, FishRarity.Rare, 1.3, 6.5, spawnWeight: 85, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Shallow },
            new FishTemplate("风啸银鲑", 22, 13, 8, FishRarity.Rare, 1.4, 7.0, spawnWeight: 82, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Middle },
            new FishTemplate("苇荡幽灵鲶", 35, 19, 12, FishRarity.Epic, 2.2, 10.0, spawnWeight: 95, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("芦湾金鳍", 35, 19, 12, FishRarity.Epic, 2.0, 9.5, spawnWeight: 90, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Middle },
            new FishTemplate("苇歌传说鲤", 50, 27, 17, FishRarity.Legendary, 2.5, 12.0, spawnWeight: 100, wariness: 0.75, power: 0.82) { PreferredDepth = WaterDepth.Shallow },
            new FishTemplate("神话·芦苇幽歌", 72, 38, 25, FishRarity.Legendary, 4.2, 17.0, spawnWeight: 118, wariness: 0.88, power: 0.94) { PreferredDepth = WaterDepth.Middle, TargetLureRecipeId = "lure_reed_song" },
        ]);
        spots["芦苇湾"] = _芦苇湾;

        // ── 夜光引渠 Lv18 · ×1.5 · Middle ──
        var _夜光引渠 = new FishingSpot("夜光引渠")
        {
            FishingTime = 2,
            RequiredLevel = 18,
            PriceMultiplier = 1.5,
            PrimaryDepth = WaterDepth.Middle,
            Description = "荧光运河 · 中层夜钓 · 荧光粉主产",
            FishRarityTable = new()
            {
                { FishRarity.Common, 50 },
                { FishRarity.Rare, 28 },
                { FishRarity.Epic, 16 },
                { FishRarity.Legendary, 6 }
            }
        };
        _夜光引渠.FishTable.AddRange([
            new FishTemplate("夜光鲤", 14, 9, 5, FishRarity.Common, 0.8, 4.0, spawnWeight: 50, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Middle },
            new FishTemplate("荧光蝌蚪", 14, 9, 5, FishRarity.Common, 0.4, 2.0, spawnWeight: 55, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Shallow },
            new FishTemplate("渠水虾", 14, 9, 5, FishRarity.Common, 0.3, 1.8, spawnWeight: 52, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Shallow },
            new FishTemplate("渠湾银鲫", 14, 9, 5, FishRarity.Common, 0.6, 3.0, spawnWeight: 48, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Shallow },
            new FishTemplate("引渠泥鳅", 22, 13, 8, FishRarity.Rare, 1.0, 5.5, spawnWeight: 90, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Shallow },
            new FishTemplate("夜光鲈", 22, 13, 8, FishRarity.Rare, 1.2, 7.0, spawnWeight: 100, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Middle },
            new FishTemplate("流光虾", 22, 13, 8, FishRarity.Rare, 0.6, 3.5, spawnWeight: 80, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Shallow },
            new FishTemplate("霁光蜓鱼", 22, 13, 8, FishRarity.Rare, 0.9, 4.5, spawnWeight: 88, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Middle },
            new FishTemplate("彩光鲑", 35, 19, 12, FishRarity.Epic, 2.0, 10.0, spawnWeight: 100, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Middle },
            new FishTemplate("运河幽灵鲶", 35, 19, 12, FishRarity.Epic, 2.5, 12.0, spawnWeight: 95, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("彩鳞鳍鱼", 35, 19, 12, FishRarity.Epic, 1.8, 9.5, spawnWeight: 92, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Middle },
            new FishTemplate("引渠金鳍", 50, 27, 17, FishRarity.Legendary, 2.5, 12.0, spawnWeight: 100, wariness: 0.75, power: 0.82) { PreferredDepth = WaterDepth.Middle },
            new FishTemplate("神话·引渠幻龙", 72, 38, 25, FishRarity.Legendary, 4.5, 20.0, spawnWeight: 120, wariness: 0.88, power: 0.94) { PreferredDepth = WaterDepth.Middle, TargetLureRecipeId = "lure_canal_dragon" },
        ]);
        spots["夜光引渠"] = _夜光引渠;

        // ── 暗涌裂谷 Lv18 · ×1.55 · Deep ──
        var _暗涌裂谷 = new FishingSpot("暗涌裂谷")
        {
            FishingTime = 2,
            RequiredLevel = 18,
            PriceMultiplier = 1.55,
            PrimaryDepth = WaterDepth.Deep,
            Description = "地壳裂谷暗涌 · 高压深层 · 裂谷矿渣",
            FishRarityTable = new()
            {
                { FishRarity.Common, 48 },
                { FishRarity.Rare, 30 },
                { FishRarity.Epic, 16 },
                { FishRarity.Legendary, 6 }
            }
        };
        _暗涌裂谷.FishTable.AddRange([
            new FishTemplate("裂谷小鳕", 14, 9, 5, FishRarity.Common, 0.5, 2.5, spawnWeight: 48, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("暗涌虾", 14, 9, 5, FishRarity.Common, 0.4, 2.0, spawnWeight: 52, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("矿渣浮游", 14, 9, 5, FishRarity.Common, 0.3, 1.5, spawnWeight: 50, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("裂隙银鲫", 14, 9, 5, FishRarity.Common, 0.55, 3.0, spawnWeight: 46, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Middle },
            new FishTemplate("暗涌鳗苗", 14, 9, 5, FishRarity.Common, 0.45, 2.2, spawnWeight: 44, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("裂谷鲈", 22, 13, 8, FishRarity.Rare, 1.2, 6.0, spawnWeight: 86, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("暗涌旗鱼", 22, 13, 8, FishRarity.Rare, 1.5, 8.5, spawnWeight: 90, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("裂隙幽灵鲶", 22, 13, 8, FishRarity.Rare, 1.1, 5.5, spawnWeight: 82, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("暗涌巨口鱼", 35, 19, 12, FishRarity.Epic, 2.4, 11.0, spawnWeight: 95, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("裂谷银鳗", 35, 19, 12, FishRarity.Epic, 2.0, 10.0, spawnWeight: 92, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("暗涌金鳞", 35, 19, 12, FishRarity.Epic, 2.6, 12.5, spawnWeight: 88, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("裂谷传说鳕", 50, 27, 17, FishRarity.Legendary, 3.0, 14.0, spawnWeight: 100, wariness: 0.75, power: 0.82) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("神话·暗涌裂谷兽", 72, 38, 25, FishRarity.Legendary, 4.8, 21.0, spawnWeight: 120, wariness: 0.88, power: 0.94) { PreferredDepth = WaterDepth.Deep, TargetLureRecipeId = "lure_rift_beast" },
        ]);
        spots["暗涌裂谷"] = _暗涌裂谷;

        // ── 极光冰湾 Lv32 · ×1.8 · Deep ──
        var _极光冰湾 = new FishingSpot("极光冰湾")
        {
            FishingTime = 2,
            RequiredLevel = 32,
            PriceMultiplier = 1.8,
            PrimaryDepth = WaterDepth.Deep,
            Description = "极光环冰湾 · 寒渊深层 · 极光冰晶",
            FishRarityTable = new()
            {
                { FishRarity.Common, 42 },
                { FishRarity.Rare, 30 },
                { FishRarity.Epic, 20 },
                { FishRarity.Legendary, 8 }
            }
        };
        _极光冰湾.FishTable.AddRange([
            new FishTemplate("雪线鲫", 14, 9, 5, FishRarity.Common, 0.6, 3.5, spawnWeight: 50, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Shallow },
            new FishTemplate("寒冰虾", 14, 9, 5, FishRarity.Common, 0.5, 2.5, spawnWeight: 55, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Shallow },
            new FishTemplate("冰吻小鳕", 14, 9, 5, FishRarity.Common, 0.4, 2.2, spawnWeight: 52, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Shallow },
            new FishTemplate("霜纹浮鱼", 14, 9, 5, FishRarity.Common, 0.35, 1.8, spawnWeight: 48, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Middle },
            new FishTemplate("冰晶鱼", 22, 13, 8, FishRarity.Rare, 1.2, 6.0, spawnWeight: 100, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("极寒银鲑", 22, 13, 8, FishRarity.Rare, 1.5, 8.0, spawnWeight: 95, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Middle },
            new FishTemplate("极光鳟", 22, 13, 8, FishRarity.Rare, 1.3, 7.0, spawnWeight: 88, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Middle },
            new FishTemplate("霜纹银鲂", 22, 13, 8, FishRarity.Rare, 1.0, 5.5, spawnWeight: 82, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Shallow },
            new FishTemplate("冰纹银鳗", 35, 19, 12, FishRarity.Epic, 1.8, 10.0, spawnWeight: 100, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("冰川巨鲈", 35, 19, 12, FishRarity.Epic, 2.5, 14.0, spawnWeight: 100, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("冰湾幽灵鳕", 35, 19, 12, FishRarity.Epic, 2.0, 11.0, spawnWeight: 90, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("寒渊巨口鱼", 35, 19, 12, FishRarity.Epic, 2.2, 12.0, spawnWeight: 93, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("霜龙传说鱼", 50, 27, 17, FishRarity.Legendary, 3.0, 15.0, spawnWeight: 100, wariness: 0.75, power: 0.82) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("神话·极光霜龙", 72, 38, 25, FishRarity.Legendary, 6.0, 25.0, spawnWeight: 120, wariness: 0.88, power: 0.94) { PreferredDepth = WaterDepth.Deep, TargetLureRecipeId = "lure_aurora_crystal" },
            new FishTemplate("归潮鳐", 35, 19, 12, FishRarity.Epic, 2.4, 12.0, spawnWeight: 30, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep },
        ]);
        spots["极光冰湾"] = _极光冰湾;

        // ── 沉船墓场 Lv32 · ×2.0 · Deep ──
        var _沉船墓场 = new FishingSpot("沉船墓场")
        {
            FishingTime = 1,
            RequiredLevel = 32,
            PriceMultiplier = 2.0,
            PrimaryDepth = WaterDepth.Deep,
            Description = "锈蚀沉船群 · 亡魂巡游 · 沉船铁锈",
            FishRarityTable = new()
            {
                { FishRarity.Common, 40 },
                { FishRarity.Rare, 32 },
                { FishRarity.Epic, 20 },
                { FishRarity.Legendary, 8 }
            }
        };
        _沉船墓场.FishTable.AddRange([
            new FishTemplate("墓场沙丁", 14, 9, 5, FishRarity.Common, 0.3, 1.5, spawnWeight: 46, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("铁锈虾", 14, 9, 5, FishRarity.Common, 0.4, 2.0, spawnWeight: 50, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("亡骸浮游", 14, 9, 5, FishRarity.Common, 0.35, 1.8, spawnWeight: 48, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("墓湾小鳕", 14, 9, 5, FishRarity.Common, 0.45, 2.5, spawnWeight: 44, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("锈迹银鲫", 22, 13, 8, FishRarity.Rare, 0.9, 4.5, spawnWeight: 84, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Middle },
            new FishTemplate("墓场电鳗", 22, 13, 8, FishRarity.Rare, 1.4, 8.0, spawnWeight: 88, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("亡魂小鱿", 22, 13, 8, FishRarity.Rare, 1.0, 6.0, spawnWeight: 80, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("暗流旗鱼", 22, 13, 8, FishRarity.Rare, 2.3, 14.0, spawnWeight: 95, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("墓场幽灵鲨", 35, 19, 12, FishRarity.Epic, 2.8, 15.0, spawnWeight: 100, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("亡魂旗鱼", 35, 19, 12, FishRarity.Epic, 2.5, 13.0, spawnWeight: 92, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("锈壳巨龟", 35, 19, 12, FishRarity.Epic, 3.0, 18.0, spawnWeight: 88, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Shallow },
            new FishTemplate("墓主传说鳕", 50, 27, 17, FishRarity.Legendary, 3.2, 16.0, spawnWeight: 100, wariness: 0.75, power: 0.82) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("神话·沉船亡魂", 72, 38, 25, FishRarity.Legendary, 5.5, 23.0, spawnWeight: 120, wariness: 0.88, power: 0.94) { PreferredDepth = WaterDepth.Deep, TargetLureRecipeId = "lure_wreck_soul" },
        ]);
        spots["沉船墓场"] = _沉船墓场;

        // ── 珊瑚暗流 Lv32 · ×1.95 · Deep ──
        var _珊瑚暗流 = new FishingSpot("珊瑚暗流")
        {
            FishingTime = 2,
            RequiredLevel = 32,
            PriceMultiplier = 1.95,
            PrimaryDepth = WaterDepth.Deep,
            Description = "珊瑚礁暗流带 · 隐蔽深层 · 珊瑚碎片",
            FishRarityTable = new()
            {
                { FishRarity.Common, 40 },
                { FishRarity.Rare, 32 },
                { FishRarity.Epic, 20 },
                { FishRarity.Legendary, 8 }
            }
        };
        _珊瑚暗流.FishTable.AddRange([
            new FishTemplate("珊瑚小丑鱼", 14, 9, 5, FishRarity.Common, 0.5, 2.5, spawnWeight: 55, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Shallow },
            new FishTemplate("暗流小虾", 14, 9, 5, FishRarity.Common, 0.3, 1.5, spawnWeight: 50, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Middle },
            new FishTemplate("礁影浮鱼", 14, 9, 5, FishRarity.Common, 0.4, 2.0, spawnWeight: 48, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Middle },
            new FishTemplate("珊瑚幼鱿", 14, 9, 5, FishRarity.Common, 0.45, 2.2, spawnWeight: 46, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("礁湾沙丁", 14, 9, 5, FishRarity.Common, 0.28, 1.4, spawnWeight: 44, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Shallow },
            new FishTemplate("礁影石斑", 22, 13, 8, FishRarity.Rare, 1.1, 6.0, spawnWeight: 88, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Middle },
            new FishTemplate("珊瑚焰鱼", 22, 13, 8, FishRarity.Rare, 1.1, 6.5, spawnWeight: 82, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Middle },
            new FishTemplate("暗流银鳗", 22, 13, 8, FishRarity.Rare, 1.5, 9.0, spawnWeight: 90, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("珊瑚暗流鳗", 35, 19, 12, FishRarity.Epic, 2.0, 11.0, spawnWeight: 95, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("礁壳巨龟", 35, 19, 12, FishRarity.Epic, 3.0, 18.0, spawnWeight: 88, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Shallow },
            new FishTemplate("珊瑚巨鱿", 35, 19, 12, FishRarity.Epic, 2.6, 13.0, spawnWeight: 92, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("珊瑚心金鳞", 50, 27, 17, FishRarity.Legendary, 2.8, 14.0, spawnWeight: 100, wariness: 0.75, power: 0.82) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("神话·珊瑚心海", 72, 38, 25, FishRarity.Legendary, 5.2, 22.0, spawnWeight: 118, wariness: 0.88, power: 0.94) { PreferredDepth = WaterDepth.Deep, TargetLureRecipeId = "lure_coral_heart" },
        ]);
        spots["珊瑚暗流"] = _珊瑚暗流;

        // ── 远礁外海 Lv45 · ×2.2 · Deep ──
        var _远礁外海 = new FishingSpot("远礁外海")
        {
            FishingTime = 1,
            RequiredLevel = 45,
            PriceMultiplier = 2.2,
            PrimaryDepth = WaterDepth.Deep,
            Description = "远礁外海开放水域 · 高周转 · 外海星核",
            FishRarityTable = new()
            {
                { FishRarity.Common, 35 },
                { FishRarity.Rare, 32 },
                { FishRarity.Epic, 22 },
                { FishRarity.Legendary, 11 }
            }
        };
        _远礁外海.FishTable.AddRange([
            new FishTemplate("礁湾鲈鱼", 14, 9, 5, FishRarity.Common, 1.0, 5.0, spawnWeight: 45, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Middle },
            new FishTemplate("远海沙丁", 14, 9, 5, FishRarity.Common, 0.3, 1.5, spawnWeight: 50, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Shallow },
            new FishTemplate("外海浮游群", 14, 9, 5, FishRarity.Common, 0.35, 1.8, spawnWeight: 48, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("礁影小鳕", 14, 9, 5, FishRarity.Common, 0.4, 2.2, spawnWeight: 44, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("深流银鳗", 22, 13, 8, FishRarity.Rare, 1.5, 9.0, spawnWeight: 100, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("深湾金枪", 22, 13, 8, FishRarity.Rare, 2.0, 12.0, spawnWeight: 95, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("巨口马鲛", 22, 13, 8, FishRarity.Rare, 1.4, 8.0, spawnWeight: 90, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("远礁蝠鲼", 35, 19, 12, FishRarity.Epic, 2.5, 16.0, spawnWeight: 100, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("远礁旗鱼", 35, 19, 12, FishRarity.Epic, 2.3, 14.0, spawnWeight: 92, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("外海巨鱿", 35, 19, 12, FishRarity.Epic, 2.8, 15.0, spawnWeight: 88, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("金鳞锦鲤", 50, 27, 17, FishRarity.Legendary, 3.0, 18.0, spawnWeight: 100, wariness: 0.75, power: 0.82) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("深湾巨口鲨", 50, 27, 17, FishRarity.Legendary, 4.0, 25.0, spawnWeight: 100, wariness: 0.75, power: 0.82) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("神话·远海沧龙", 72, 38, 25, FishRarity.Legendary, 6.5, 28.0, spawnWeight: 120, wariness: 0.88, power: 0.94) { PreferredDepth = WaterDepth.Deep, TargetLureRecipeId = "lure_reef_leviathan" },
            new FishTemplate("神话·金鳞海皇", 72, 38, 25, FishRarity.Legendary, 5.5, 24.0, spawnWeight: 115, wariness: 0.88, power: 0.94) { PreferredDepth = WaterDepth.Deep, TargetLureRecipeId = "lure_sea_emperor" },
            new FishTemplate("跨域银鳗", 22, 13, 8, FishRarity.Rare, 1.6, 9.5, spawnWeight: 35, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("归潮鳐", 35, 19, 12, FishRarity.Epic, 2.4, 12.0, spawnWeight: 30, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep },
        ]);
        spots["远礁外海"] = _远礁外海;

        // ── 深渊回廊 Lv45 · ×2.5 · Deep ──
        var _深渊回廊 = new FishingSpot("深渊回廊")
        {
            FishingTime = 1,
            RequiredLevel = 45,
            PriceMultiplier = 2.5,
            PrimaryDepth = WaterDepth.Deep,
            Description = "海底裂隙回廊 · 凝胶矿脉 · 深渊凝胶",
            FishRarityTable = new()
            {
                { FishRarity.Common, 32 },
                { FishRarity.Rare, 34 },
                { FishRarity.Epic, 24 },
                { FishRarity.Legendary, 10 }
            }
        };
        _深渊回廊.FishTable.AddRange([
            new FishTemplate("回廊小鳕", 14, 9, 5, FishRarity.Common, 0.4, 2.2, spawnWeight: 44, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("深渊浮游", 14, 9, 5, FishRarity.Common, 0.35, 1.8, spawnWeight: 50, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("凝胶幼体", 14, 9, 5, FishRarity.Common, 0.3, 1.5, spawnWeight: 48, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("回廊银鲫", 14, 9, 5, FishRarity.Common, 0.5, 2.8, spawnWeight: 46, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Middle },
            new FishTemplate("深渊鲈", 22, 13, 8, FishRarity.Rare, 1.3, 7.0, spawnWeight: 86, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("回廊电鳗", 22, 13, 8, FishRarity.Rare, 1.6, 9.5, spawnWeight: 90, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("凝胶鱿", 22, 13, 8, FishRarity.Rare, 1.2, 7.5, spawnWeight: 84, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("回廊巨口鱼", 35, 19, 12, FishRarity.Epic, 2.6, 13.0, spawnWeight: 95, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("深渊安康", 35, 19, 12, FishRarity.Epic, 3.0, 14.0, spawnWeight: 92, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("回廊蝠鲼", 35, 19, 12, FishRarity.Epic, 2.8, 15.0, spawnWeight: 88, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("回廊传说鲨", 50, 27, 17, FishRarity.Legendary, 3.5, 20.0, spawnWeight: 100, wariness: 0.75, power: 0.82) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("神话·深渊巡礼者", 72, 38, 25, FishRarity.Legendary, 6.0, 26.0, spawnWeight: 120, wariness: 0.88, power: 0.94) { PreferredDepth = WaterDepth.Deep, TargetLureRecipeId = "lure_abyss_walker" },
            new FishTemplate("跨域银鳗", 22, 13, 8, FishRarity.Rare, 1.6, 9.5, spawnWeight: 35, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("星尘巡游鱼", 22, 13, 8, FishRarity.Rare, 1.2, 7.0, spawnWeight: 28, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Deep },
        ]);
        spots["深渊回廊"] = _深渊回廊;

        // ── 星潮海沟 Lv45 · ×2.6 · Deep ──
        var _星潮海沟 = new FishingSpot("星潮海沟")
        {
            FishingTime = 1,
            RequiredLevel = 45,
            PriceMultiplier = 2.6,
            PrimaryDepth = WaterDepth.Deep,
            Description = "星潮引力海沟 · 潮汐异种 · 星潮碎片",
            FishRarityTable = new()
            {
                { FishRarity.Common, 30 },
                { FishRarity.Rare, 34 },
                { FishRarity.Epic, 26 },
                { FishRarity.Legendary, 10 }
            }
        };
        _星潮海沟.FishTable.AddRange([
            new FishTemplate("星潮沙丁", 14, 9, 5, FishRarity.Common, 0.3, 1.5, spawnWeight: 46, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("潮汐小虾", 14, 9, 5, FishRarity.Common, 0.35, 1.8, spawnWeight: 50, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("星尘浮游", 14, 9, 5, FishRarity.Common, 0.28, 1.4, spawnWeight: 48, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("海沟银鲫", 14, 9, 5, FishRarity.Common, 0.45, 2.5, spawnWeight: 44, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Middle },
            new FishTemplate("星潮鲈", 22, 13, 8, FishRarity.Rare, 1.4, 7.5, spawnWeight: 88, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("潮汐旗鱼", 22, 13, 8, FishRarity.Rare, 1.8, 10.0, spawnWeight: 92, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("星尘鳗", 22, 13, 8, FishRarity.Rare, 1.5, 9.0, spawnWeight: 86, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("海沟巨口鱼", 35, 19, 12, FishRarity.Epic, 2.8, 14.0, spawnWeight: 95, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("星潮蝠鲼", 35, 19, 12, FishRarity.Epic, 3.0, 16.0, spawnWeight: 90, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("潮汐幽灵鲨", 35, 19, 12, FishRarity.Epic, 2.6, 13.5, spawnWeight: 88, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("星潮传说鳕", 50, 27, 17, FishRarity.Legendary, 3.8, 22.0, spawnWeight: 100, wariness: 0.75, power: 0.82) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("神话·星潮巨兽", 72, 38, 25, FishRarity.Legendary, 6.2, 27.0, spawnWeight: 120, wariness: 0.88, power: 0.94) { PreferredDepth = WaterDepth.Deep, TargetLureRecipeId = "lure_star_tide" },
            new FishTemplate("跨域银鳗", 22, 13, 8, FishRarity.Rare, 1.6, 9.5, spawnWeight: 35, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("归潮鳐", 35, 19, 12, FishRarity.Epic, 2.4, 12.0, spawnWeight: 30, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("星尘巡游鱼", 22, 13, 8, FishRarity.Rare, 1.2, 7.0, spawnWeight: 28, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Deep },
        ]);
        spots["星潮海沟"] = _星潮海沟;

        // ── 虚空钓域 Lv60 · ×3.0 · Deep ──
        var _虚空钓域 = new FishingSpot("虚空钓域")
        {
            FishingTime = 1,
            RequiredLevel = 60,
            PriceMultiplier = 3.0,
            PrimaryDepth = WaterDepth.Deep,
            Description = "终局虚空水域 · 全神话解锁 · 虚空纤维终极产",
            FishRarityTable = new()
            {
                { FishRarity.Common, 28 },
                { FishRarity.Rare, 30 },
                { FishRarity.Epic, 28 },
                { FishRarity.Legendary, 14 }
            }
        };
        _虚空钓域.FishTable.AddRange([
            new FishTemplate("虚空浮游", 14, 9, 5, FishRarity.Common, 0.4, 2.0, spawnWeight: 42, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("裂隙小鳕", 14, 9, 5, FishRarity.Common, 0.45, 2.5, spawnWeight: 44, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("虚影虾", 14, 9, 5, FishRarity.Common, 0.35, 1.8, spawnWeight: 48, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("虚空银鲫", 14, 9, 5, FishRarity.Common, 0.5, 3.0, spawnWeight: 46, wariness: 0.08, power: 0.06) { PreferredDepth = WaterDepth.Middle },
            new FishTemplate("虚空鲈", 22, 13, 8, FishRarity.Rare, 1.5, 8.0, spawnWeight: 85, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("裂隙电鳗", 22, 13, 8, FishRarity.Rare, 1.8, 10.5, spawnWeight: 90, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("虚影鱿", 22, 13, 8, FishRarity.Rare, 1.3, 8.0, spawnWeight: 82, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("虚空巨口鱼", 35, 19, 12, FishRarity.Epic, 3.0, 15.0, spawnWeight: 95, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("裂隙蝠鲼", 35, 19, 12, FishRarity.Epic, 3.2, 17.0, spawnWeight: 92, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("虚空幽灵鲨", 35, 19, 12, FishRarity.Epic, 2.8, 14.5, spawnWeight: 88, wariness: 0.55, power: 0.52) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("终焉传说鱼", 50, 27, 17, FishRarity.Legendary, 4.5, 28.0, spawnWeight: 100, wariness: 0.75, power: 0.82) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("虚空鲸影", 50, 27, 17, FishRarity.Legendary, 5.0, 32.0, spawnWeight: 95, wariness: 0.75, power: 0.82) { PreferredDepth = WaterDepth.Deep },
            new FishTemplate("神话·虚空钓主", 72, 38, 25, FishRarity.Legendary, 7.0, 30.0, spawnWeight: 125, wariness: 0.88, power: 0.94) { PreferredDepth = WaterDepth.Deep, TargetLureRecipeId = "lure_void_master" },
            new FishTemplate("神话·终焉鲸歌", 72, 38, 25, FishRarity.Legendary, 6.8, 29.0, spawnWeight: 122, wariness: 0.88, power: 0.94) { PreferredDepth = WaterDepth.Deep, TargetLureRecipeId = "lure_void_whale" },
            new FishTemplate("星尘巡游鱼", 22, 13, 8, FishRarity.Rare, 1.2, 7.0, spawnWeight: 28, wariness: 0.3, power: 0.28) { PreferredDepth = WaterDepth.Deep },
        ]);
        spots["虚空钓域"] = _虚空钓域;

    }

    private static IReadOnlyDictionary<string, string[]> PreviewFishMap => new Dictionary<string, string[]>
    {
        ["静溪"] = ["野生鲫鱼", "彩虹鳟鱼", "黄金锦鲤"],
        ["浅塘"] = ["浅塘鲫", "浅塘鲤", "塘主金鲤"],
        ["雾海深渊"] = ["夜光乌贼", "幽蓝安康", "雾海锦鳞"],
        ["芦苇湾"] = ["芦苇鲈", "苇荡幽灵鲶", "苇歌传说鲤"],
        ["夜光引渠"] = ["引渠泥鳅", "彩光鲑", "引渠金鳍"],
        ["暗涌裂谷"] = ["暗涌旗鱼", "暗涌巨口鱼", "裂谷传说鳕"],
        ["极光冰湾"] = ["冰晶鱼", "冰纹银鳗", "霜龙传说鱼"],
        ["沉船墓场"] = ["暗流旗鱼", "墓场幽灵鲨", "墓主传说鳕"],
        ["珊瑚暗流"] = ["礁影石斑", "珊瑚暗流鳗", "珊瑚心金鳞"],
        ["远礁外海"] = ["深流银鳗", "金鳞锦鲤", "深湾巨口鲨"],
        ["深渊回廊"] = ["回廊电鳗", "深渊安康", "回廊传说鲨"],
        ["星潮海沟"] = ["潮汐旗鱼", "星潮蝠鲼", "星潮传说鳕"],
        ["虚空钓域"] = ["虚空巨口鱼", "终焉传说鱼", "神话·虚空钓主"],
    };
}
