namespace CyberPetApp.Models;

/// <summary>T6~T10 装备目录与炼金配方（500h 毕业曲线：T8 图鉴75% · T10 图鉴95%+全神话）。</summary>
internal static class GearT6T10Data
{
    internal static readonly RodSpec[] ExtraRods =
    [
        new("“暗涌”高频感度插接竿", 4.2, 115, 5, 38, 0, "炼金 T6 · 引渠特化", GearTier.T6, ShopAvailable: false, CraftOnly: true, RequiredLicenseSpot: "地下暗河", RequiredCatLevel: 24),
        new("“钛星”记忆钛合金竿", 4.5, 125, 5, 40, 0, "炼金 T6 · 敏锐+45%", GearTier.T6, ShopAvailable: false, CraftOnly: true, RequiredDexSpot: "地下暗河", RequiredDexPercent: 0.55, RequiredCatLevel: 24),
        new("“不融冰”极寒碳纤维竿", 4.8, 140, 5, 46, 0, "炼金 T7 · 冰湾特化", GearTier.T7, ShopAvailable: false, CraftOnly: true, RequiredLicenseSpot: "极光冰湾", RequiredCatLevel: 30),
        new("“高能重力”偏振抛投竿", 5.0, 150, 5, 48, 0, "炼金 T7 · 深层+敏锐", GearTier.T7, ShopAvailable: false, CraftOnly: true, RequiredDexSpot: "极光冰湾", RequiredDexPercent: 0.60, RequiredCatLevel: 30),
        new("“海怪肋骨”重碳插接巨竿", 5.3, 165, 5, 54, 0, "炼金 T8 · 钓重165kg", GearTier.T8, ShopAvailable: false, CraftOnly: true, RequiredOverallDexPercent: 0.75, RequiredCatLevel: 36),
        new("“极光追猎者”微导环竿", 5.1, 158, 5, 52, 0, "炼金 T8 · 冰湾神话向", GearTier.T8, ShopAvailable: false, CraftOnly: true, RequiredOverallDexPercent: 0.75, RequiredLicenseSpot: "极光冰湾", RequiredCatLevel: 36),
        new("“万象归一”碳纤维终极枪柄", 5.6, 185, 5, 60, 0, "炼金 T9 · 敏锐+56%", GearTier.T9, ShopAvailable: false, CraftOnly: true, RequiredOverallDexPercent: 0.85, RequiredCatLevel: 42, RequiredMythicCaught: 1),
        new("“裂隙”高维编织便携旅竿", 5.8, 195, 5, 62, 0, "炼金 T9 · 抛投5+", GearTier.T9, ShopAvailable: false, CraftOnly: true, RequiredOverallDexPercent: 0.85, RequiredLicenseSpot: "远礁外海", RequiredCatLevel: 42, RequiredMythicCaught: 1),
        new("“利维坦之握”海钓金枪重竿", 6.2, 220, 5, 68, 0, "终极竿 · 抛投5 · 钓重220kg", GearTier.T10, ShopAvailable: false, CraftOnly: true, RequiredOverallDexPercent: 0.95, RequiredCatLevel: 50, RequiredAllMythic: true),
        new("“太弦”反重力微导架抛投竿", 6.5, 250, 5, 70, 0, "毕业竿 · 神话素材终极", GearTier.T10, ShopAvailable: false, CraftOnly: true, RequiredOverallDexPercent: 0.95, RequiredCatLevel: 50, RequiredAllMythic: true),
    ];

    internal static readonly ReelSpec[] ExtraReels =
    [
        new("“荧流”油压阻尼纺车轮", 14, 9.2, 62, 0.86, 38, 0, "炼金 T6 · 线杯62kg", GearTier.T6, ShopAvailable: false, CraftOnly: true, RequiredLicenseSpot: "地下暗河", RequiredCatLevel: 24),
        new("“陨星”钛镂空轻量化轮", 15, 9.8, 68, 0.89, 40, 0, "炼金 T6 · 高顺滑", GearTier.T6, ShopAvailable: false, CraftOnly: true, RequiredDexSpot: "地下暗河", RequiredDexPercent: 0.55, RequiredCatLevel: 24),
        new("“极地”防寒抗低温齿轮箱", 17, 10.2, 75, 0.91, 46, 0, "炼金 T7 · 冰湾轮", GearTier.T7, ShopAvailable: false, CraftOnly: true, RequiredLicenseSpot: "极光冰湾", RequiredCatLevel: 30),
        new("“裂变”双线杯速比调节轮", 18, 10.5, 82, 0.93, 48, 0, "炼金 T7 · 卸力强化", GearTier.T7, ShopAvailable: false, CraftOnly: true, RequiredDexSpot: "极光冰湾", RequiredDexPercent: 0.60, RequiredCatLevel: 30),
        new("“沧溟”万级深海大型纺车", 20, 11.0, 95, 0.94, 54, 0, "炼金 T8 · 线杯95kg", GearTier.T8, ShopAvailable: false, CraftOnly: true, RequiredOverallDexPercent: 0.75, RequiredCatLevel: 36),
        new("“无声”碳纤多盘刹车轮", 19, 10.8, 90, 0.93, 52, 0, "炼金 T8 · 冰湾特化轮", GearTier.T8, ShopAvailable: false, CraftOnly: true, RequiredOverallDexPercent: 0.75, RequiredCatLevel: 36),
        new("“极限”航天级阳极氧化飞线轮", 22, 11.5, 110, 0.96, 60, 0, "炼金 T9 · 线杯110kg", GearTier.T9, ShopAvailable: false, CraftOnly: true, RequiredOverallDexPercent: 0.85, RequiredLicenseSpot: "远礁外海", RequiredCatLevel: 42, RequiredMythicCaught: 1),
        new("“脉冲交互”微调双煞水滴", 21, 11.2, 105, 0.95, 62, 0, "炼金 T9 · 远礁向", GearTier.T9, ShopAvailable: false, CraftOnly: true, RequiredOverallDexPercent: 0.85, RequiredLicenseSpot: "远礁外海", RequiredCatLevel: 42, RequiredMythicCaught: 1),
        new("“怒潮”数字闭环电绞轮", 24, 12.0, 130, 0.98, 68, 0, "毕业轮 · 线杯130kg", GearTier.T10, ShopAvailable: false, CraftOnly: true, RequiredOverallDexPercent: 0.95, RequiredCatLevel: 50, RequiredAllMythic: true),
        new("“天枢”磁悬浮无摩擦线轴轮", 23, 11.8, 125, 0.97, 70, 0, "毕业轮 · 神话卸力", GearTier.T10, ShopAvailable: false, CraftOnly: true, RequiredOverallDexPercent: 0.95, RequiredCatLevel: 50, RequiredAllMythic: true),
    ];

    internal static readonly LineSpec[] ExtraLines =
    [
        new("“极速”低风阻抛投PE线", 75, 1.9, 0.20, 0.52, WaterDepth.Deep, 38, 0, "炼金 T6 · 强度75kg", GearTier.T6, ShopAvailable: false, CraftOnly: true, RequiredLicenseSpot: "地下暗河", RequiredCatLevel: 24),
        new("“星屑”高感度混合前导线", 80, 2.0, 0.22, 0.55, WaterDepth.Deep, 40, 0, "炼金 T6 · 耐磨55%", GearTier.T6, ShopAvailable: false, CraftOnly: true, RequiredDexSpot: "地下暗河", RequiredDexPercent: 0.55, RequiredCatLevel: 24),
        new("“防冻”氟素树脂涂层线", 95, 2.1, 0.24, 0.58, WaterDepth.Deep, 46, 0, "炼金 T7 · 强度95kg", GearTier.T7, ShopAvailable: false, CraftOnly: true, RequiredLicenseSpot: "极光冰湾", RequiredCatLevel: 30),
        new("“回声”震动放大碳素线", 100, 2.2, 0.26, 0.60, WaterDepth.Deep, 48, 0, "炼金 T7 · 高敏锐", GearTier.T7, ShopAvailable: false, CraftOnly: true, RequiredDexSpot: "极光冰湾", RequiredDexPercent: 0.60, RequiredCatLevel: 30),
        new("“海蛇皮”复合耐磨合股线", 120, 2.4, 0.28, 0.65, WaterDepth.Deep, 54, 0, "炼金 T8 · 强度120kg", GearTier.T8, ShopAvailable: false, CraftOnly: true, RequiredOverallDexPercent: 0.75, RequiredCatLevel: 36),
        new("“偏光”深渊水色隐蔽前导", 115, 2.3, 0.27, 0.63, WaterDepth.Deep, 52, 0, "炼金 T8 · 冰湾线", GearTier.T8, ShopAvailable: false, CraftOnly: true, RequiredOverallDexPercent: 0.75, RequiredCatLevel: 36),
        new("“极细”十二编超顺滑PE线", 145, 2.6, 0.30, 0.70, WaterDepth.Deep, 60, 0, "炼金 T9 · 强度145kg", GearTier.T9, ShopAvailable: false, CraftOnly: true, RequiredOverallDexPercent: 0.85, RequiredLicenseSpot: "远礁外海", RequiredCatLevel: 42, RequiredMythicCaught: 1),
        new("“零延展”纳米级碳晶线", 150, 2.7, 0.32, 0.72, WaterDepth.Deep, 62, 0, "炼金 T9 · 耐磨72%", GearTier.T9, ShopAvailable: false, CraftOnly: true, RequiredOverallDexPercent: 0.85, RequiredLicenseSpot: "远礁外海", RequiredCatLevel: 42, RequiredMythicCaught: 1),
        new("“空天”高分子超密分子线", 180, 2.9, 0.35, 0.78, WaterDepth.Deep, 68, 0, "毕业线 · 强度180kg", GearTier.T10, ShopAvailable: false, CraftOnly: true, RequiredOverallDexPercent: 0.95, RequiredCatLevel: 50, RequiredAllMythic: true),
        new("“永恒”钛晶编织超耐磨巨线", 200, 3.0, 0.38, 0.80, WaterDepth.Deep, 70, 0, "毕业线 · 神话耐磨", GearTier.T10, ShopAvailable: false, CraftOnly: true, RequiredOverallDexPercent: 0.95, RequiredCatLevel: 50, RequiredAllMythic: true),
    ];

    internal static readonly LureSpec[] ExtraLures =
    [
        new("“亮闪闪”金属旋转复合亮片", 0.48, 1.1, WaterDepth.Deep, 8, 38, 2, 0, "炼金 T6 · 品质+110%", GearTier.T6, ShopAvailable: false, CraftOnly: true, RequiredLicenseSpot: "地下暗河", RequiredCatLevel: 24),
        new("“颤流”偏心超低频VIB", 0.52, 1.25, WaterDepth.Deep, 7, 40, 2, 0, "炼金 T6 · 引渠特化饵", GearTier.T6, ShopAvailable: false, CraftOnly: true, RequiredDexSpot: "地下暗河", RequiredDexPercent: 0.55, RequiredCatLevel: 24, MythicBonus: 0.03),
        new("“破冰者”深海慢摇铁板", 0.56, 1.35, WaterDepth.Deep, 7, 46, 2, 0, "炼金 T7 · 品质+135%", GearTier.T7, ShopAvailable: false, CraftOnly: true, RequiredLicenseSpot: "极光冰湾", RequiredCatLevel: 30, MythicBonus: 0.04),
        new("“多节斑马”缓沉铅笔饵", 0.58, 1.45, WaterDepth.Deep, 6, 48, 2, 0, "炼金 T7 · 深层 lure", GearTier.T7, ShopAvailable: false, CraftOnly: true, RequiredDexSpot: "极光冰湾", RequiredDexPercent: 0.60, RequiredCatLevel: 30, MythicBonus: 0.05),
        new("“疯狂乌贼”发光触须拖钓饵", 0.60, 1.55, WaterDepth.Deep, 5, 54, 2, 0, "炼金 T8 · 神话饵率+6%", GearTier.T8, ShopAvailable: false, CraftOnly: true, RequiredOverallDexPercent: 0.75, RequiredCatLevel: 36, MythicBonus: 0.06),
        new("“闷响”内置钨珠避障小胖子", 0.58, 1.50, WaterDepth.Deep, 6, 52, 2, 0, "炼金 T8 · 冰湾饵", GearTier.T8, ShopAvailable: false, CraftOnly: true, RequiredOverallDexPercent: 0.75, RequiredCatLevel: 36, MythicBonus: 0.05),
        new("“极速羽毛”低阻防缠绕飞蝇", 0.62, 1.65, WaterDepth.Deep, 5, 60, 2, 0, "炼金 T9 · 神话饵率+7%", GearTier.T9, ShopAvailable: false, CraftOnly: true, RequiredOverallDexPercent: 0.85, RequiredLicenseSpot: "远礁外海", RequiredCatLevel: 42, RequiredMythicCaught: 1, MythicBonus: 0.07),
        new("“幻影”多节仿生活性多段鱼", 0.64, 1.75, WaterDepth.Deep, 4, 62, 2, 0, "炼金 T9 · 远礁向", GearTier.T9, ShopAvailable: false, CraftOnly: true, RequiredOverallDexPercent: 0.85, RequiredLicenseSpot: "远礁外海", RequiredCatLevel: 42, RequiredMythicCaught: 1, MythicBonus: 0.08),
        new("“终极撕裂者”深海巨型波扒", 0.68, 1.90, WaterDepth.Deep, 4, 68, 2, 0, "毕业饵 · 神话饵率+10%", GearTier.T10, ShopAvailable: false, CraftOnly: true, RequiredOverallDexPercent: 0.95, RequiredCatLevel: 50, RequiredAllMythic: true, MythicBonus: 0.10),
        new("“星海之光”变频自发光仿生饵", 0.70, 2.00, WaterDepth.Deep, 3, 70, 2, 0, "毕业饵 · 神话终极", GearTier.T10, ShopAvailable: false, CraftOnly: true, RequiredOverallDexPercent: 0.95, RequiredCatLevel: 50, RequiredAllMythic: true, MythicBonus: 0.12),
    ];

    internal static readonly GearCraftRecipe[] ExtraCraftRecipes =
    [
        // ── T6 四槽（引渠许可 · 钓鱼32 · 猫24）──
        new("craft_rod_t6_canal", "“暗涌”高频感度插接竿", GearCraftSlot.Rod, "“暗涌”高频感度插接竿", GearTier.T6,
            [new FishRequirement("暗河金丝鲃", 1, FishRarity.Legendary, "地下暗河")],
            [new(AlchemyMaterials.CanalGlowPowder, 4), new(AlchemyMaterials.CarbonFiber, 4), new(AlchemyMaterials.Resin, 2)],
            EconomySinks.AlchemyGearCraftT6Cost, 32, 24, null, 0, "地下暗河", 0,
            "引渠传说 + 地下荧光孢子粉×4 → “暗涌”高频感度插接竿"),
        new("craft_rod_t6_star", "“钛星”记忆钛合金竿", GearCraftSlot.Rod, "“钛星”记忆钛合金竿", GearTier.T6,
            [new FishRequirement("引水五彩鲑", 1, FishRarity.Epic, "地下暗河")],
            [new(AlchemyMaterials.StarfallAlloy, 3), new(AlchemyMaterials.CanalGlowPowder, 3)],
            EconomySinks.AlchemyGearCraftT6Cost + 3000, 32, 24, "地下暗河", 0.55, null, 0,
            "引渠史诗 + 星陨粗铁胚 → “钛星”记忆钛合金竿"),
        new("craft_reel_t6_canal", "“荧流”油压阻尼纺车轮", GearCraftSlot.Reel, "“荧流”油压阻尼纺车轮", GearTier.T6,
            [],
            [new(AlchemyMaterials.GearSet, 4), new(AlchemyMaterials.CanalGlowPowder, 3), new(AlchemyMaterials.Bearing, 2)],
            EconomySinks.AlchemyGearCraftT6Cost, 32, 24, null, 0, "地下暗河", 0,
            "荧光粉 + 生锈齿轮组 → “荧流”油压阻尼纺车轮"),
        new("craft_reel_t6_star", "“陨星”钛镂空轻量化轮", GearCraftSlot.Reel, "“陨星”钛镂空轻量化轮", GearTier.T6,
            [new FishRequirement("夜行黑棘鲈", 2, FishRarity.Rare, "地下暗河")],
            [new(AlchemyMaterials.GearSet, 3), new(AlchemyMaterials.StarfallAlloy, 2)],
            EconomySinks.AlchemyGearCraftT6Cost + 2000, 32, 24, "地下暗河", 0.55, null, 0,
            "引渠稀有×2 + 星陨粗铁胚 → “陨星”钛镂空轻量化轮"),
        new("craft_line_t6_canal", "“极速”低风阻抛投PE线", GearCraftSlot.Line, "“极速”低风阻抛投PE线", GearTier.T6,
            [],
            [new(AlchemyMaterials.NylonFilament, 8), new(AlchemyMaterials.CanalGlowPowder, 4)],
            EconomySinks.AlchemyGearCraftT6Cost, 32, 24, null, 0, "地下暗河", 0,
            "荧光粉 + 工业尼龙单丝 → “极速”低风阻抛投PE线"),
        new("craft_line_t6_star", "“星屑”高感度混合前导线", GearCraftSlot.Line, "“星屑”高感度混合前导线", GearTier.T6,
            [new FishRequirement("*", 3, FishRarity.Rare, "地下暗河")],
            [new(AlchemyMaterials.StarfallAlloy, 3), new(AlchemyMaterials.NylonFilament, 5)],
            EconomySinks.AlchemyGearCraftT6Cost, 32, 24, "地下暗河", 0.55, null, 0,
            "引渠稀有×3 + 星陨粗铁胚 → “星屑”高感度混合前导线"),
        new("craft_lure_t6_canal", "“亮闪闪”金属旋转复合亮片", GearCraftSlot.Lure, "“亮闪闪”金属旋转复合亮片", GearTier.T6,
            [new FishRequirement("*", 4, FishRarity.Rare, "地下暗河")],
            [new(AlchemyMaterials.CanalGlowPowder, 5), new(AlchemyMaterials.ScalePowder, 4)],
            EconomySinks.AlchemyGearCraftT6Cost, 32, 24, null, 0, "地下暗河", 0,
            "引渠稀有×4 + 荧光粉 → “亮闪闪”金属旋转复合亮片×2"),
        new("craft_lure_t6_star", "“颤流”偏心超低频VIB", GearCraftSlot.Lure, "“颤流”偏心超低频VIB", GearTier.T6,
            [new FishRequirement("地底粉红鲵", 1, FishRarity.Epic, "地下暗河")],
            [new(AlchemyMaterials.StarfallAlloy, 4), new(AlchemyMaterials.ScalePowder, 5)],
            EconomySinks.AlchemyGearCraftT6Cost + 2500, 32, 24, "地下暗河", 0.55, null, 0,
            "引渠史诗 + 星陨粗铁胚 → “颤流”偏心超低频VIB×2"),

        // ── T7 四槽（冰湾许可 · 钓鱼40 · 猫30）──
        new("craft_rod_t7_void", "“不融冰”极寒碳纤维竿", GearCraftSlot.Rod, "“不融冰”极寒碳纤维竿", GearTier.T7,
            [new FishRequirement("极光冰川巨鳎", 1, FishRarity.Legendary, "极光冰湾")],
            [new(AlchemyMaterials.AuroraIceCrystal, 4), new(AlchemyMaterials.CarbonFiber, 5)],
            EconomySinks.AlchemyGearCraftT7Cost, 40, 30, null, 0, "极光冰湾", 0,
            "冰湾传说 + 不融极地冰晶×4 → “不融冰”极寒碳纤维竿"),
        new("craft_rod_t7_battle", "“高能重力”偏振抛投竿", GearCraftSlot.Rod, "“高能重力”偏振抛投竿", GearTier.T7,
            [new FishRequirement("北极重水鲈", 1, FishRarity.Epic, "极光冰湾")],
            [new(AlchemyMaterials.VoidCore, 3), new(AlchemyMaterials.AuroraIceCrystal, 2)],
            EconomySinks.AlchemyGearCraftT7Cost + 5000, 40, 30, "极光冰湾", 0.60, null, 0,
            "冰湾史诗 + 裂隙虚空原核 → “高能重力”偏振抛投竿"),
        new("craft_reel_t7_void", "“极地”防寒抗低温齿轮箱", GearCraftSlot.Reel, "“极地”防寒抗低温齿轮箱", GearTier.T7,
            [],
            [new(AlchemyMaterials.GearSet, 5), new(AlchemyMaterials.AuroraIceCrystal, 3), new(AlchemyMaterials.Bearing, 3)],
            EconomySinks.AlchemyGearCraftT7Cost, 40, 30, null, 0, "极光冰湾", 0,
            "冰晶 + 生锈齿轮组 → “极地”防寒抗低温齿轮箱"),
        new("craft_reel_t7_hydro", "“裂变”双线杯速比调节轮", GearCraftSlot.Reel, "“裂变”双线杯速比调节轮", GearTier.T7,
            [new FishRequirement("冰川蛇鳕", 1, FishRarity.Epic, "极光冰湾")],
            [new(AlchemyMaterials.VoidCore, 2), new(AlchemyMaterials.GearSet, 3)],
            EconomySinks.AlchemyGearCraftT7Cost + 4000, 40, 30, "极光冰湾", 0.60, null, 0,
            "冰湾史诗 + 裂隙虚空原核 → “裂变”双线杯速比调节轮"),
        new("craft_line_t7_void", "“防冻”氟素树脂涂层线", GearCraftSlot.Line, "“防冻”氟素树脂涂层线", GearTier.T7,
            [],
            [new(AlchemyMaterials.NylonFilament, 10), new(AlchemyMaterials.AuroraIceCrystal, 4)],
            EconomySinks.AlchemyGearCraftT7Cost, 40, 30, null, 0, "极光冰湾", 0,
            "冰晶 + 工业尼龙单丝 → “防冻”氟素树脂涂层线"),
        new("craft_line_t7_guide", "“回声”震动放大碳素线", GearCraftSlot.Line, "“回声”震动放大碳素线", GearTier.T7,
            [new FishRequirement("*", 2, FishRarity.Epic, "极光冰湾")],
            [new(AlchemyMaterials.VoidCore, 3), new(AlchemyMaterials.CarbonFiber, 4)],
            EconomySinks.AlchemyGearCraftT7Cost, 40, 30, "极光冰湾", 0.60, null, 0,
            "冰湾史诗×2 + 裂隙虚空原核 → “回声”震动放大碳素线"),
        new("craft_lure_t7_void", "“破冰者”深海慢摇铁板", GearCraftSlot.Lure, "“破冰者”深海慢摇铁板", GearTier.T7,
            [new FishRequirement("*", 3, FishRarity.Rare, "极光冰湾")],
            [new(AlchemyMaterials.AuroraIceCrystal, 4), new(AlchemyMaterials.ScalePowder, 5)],
            EconomySinks.AlchemyGearCraftT7Cost, 40, 30, null, 0, "极光冰湾", 0,
            "冰湾稀有×3 + 冰晶 → “破冰者”深海慢摇铁板×2"),
        new("craft_lure_t7_mimic", "“多节斑马”缓沉铅笔饵", GearCraftSlot.Lure, "“多节斑马”缓沉铅笔饵", GearTier.T7,
            [new FishRequirement("深渊巨口宽咽鱼", 1, FishRarity.Epic, "极光冰湾")],
            [new(AlchemyMaterials.VoidCore, 3), new(AlchemyMaterials.MythScalePowder, 1)],
            EconomySinks.AlchemyGearCraftT7Cost + 6000, 40, 30, "极光冰湾", 0.60, null, 0,
            "冰湾史诗 + 裂隙虚空原核 → “多节斑马”缓沉铅笔饵×2"),

        // ── T8 四槽（全图鉴75% · 钓鱼48 · 猫36）──
        new("craft_rod_t8_dragon", "“海怪肋骨”重碳插接巨竿", GearCraftSlot.Rod, "“海怪肋骨”重碳插接巨竿", GearTier.T8,
            [new FishRequirement("大白鲨", 1, FishRarity.Legendary, "远礁外海")],
            [new(AlchemyMaterials.AbyssGel, 5), new(AlchemyMaterials.DeepSeaCrystal, 4), new(AlchemyMaterials.MythScalePowder, 2)],
            EconomySinks.AlchemyGearCraftT8Cost, 48, 36, null, 0, null, 0.75,
            "远礁传说 + 深渊巨兽粘液 → “海怪肋骨”重碳插接巨竿"),
        new("craft_rod_t8_oracle", "“极光追猎者”微导环竿", GearCraftSlot.Rod, "“极光追猎者”微导环竿", GearTier.T8,
            [new FishRequirement("墓场带鱼王", 1, FishRarity.Epic, "沉船墓场")],
            [new(AlchemyMaterials.WreckRust, 6), new(AlchemyMaterials.AbyssGel, 3)],
            EconomySinks.AlchemyGearCraftT8Cost, 48, 36, null, 0, null, 0.75,
            "墓场史诗 + 百年沉船铁皮 → “极光追猎者”微导环竿"),
        new("craft_reel_t8_abyss", "“沧溟”万级深海大型纺车", GearCraftSlot.Reel, "“沧溟”万级深海大型纺车", GearTier.T8,
            [],
            [new(AlchemyMaterials.GearSet, 6), new(AlchemyMaterials.AbyssGel, 3), new(AlchemyMaterials.Bearing, 4)],
            EconomySinks.AlchemyGearCraftT8Cost, 48, 36, null, 0, null, 0.75,
            "深渊巨兽粘液 + 生锈齿轮组 → “沧溟”万级深海大型纺车"),
        new("craft_reel_t8_oracle", "“无声”碳纤多盘刹车轮", GearCraftSlot.Reel, "“无声”碳纤多盘刹车轮", GearTier.T8,
            [new FishRequirement("深海皱鳃鲨", 1, FishRarity.Epic, "沉船墓场")],
            [new(AlchemyMaterials.GearSet, 4), new(AlchemyMaterials.WreckRust, 4)],
            EconomySinks.AlchemyGearCraftT8Cost + 8000, 48, 36, null, 0, null, 0.75,
            "墓场史诗 + 铁锈 → “无声”碳纤多盘刹车轮"),
        new("craft_line_t8_dragon", "“海蛇皮”复合耐磨合股线", GearCraftSlot.Line, "“海蛇皮”复合耐磨合股线", GearTier.T8,
            [],
            [new(AlchemyMaterials.NylonFilament, 12), new(AlchemyMaterials.AbyssGel, 4)],
            EconomySinks.AlchemyGearCraftT8Cost, 48, 36, null, 0, null, 0.75,
            "深渊巨兽粘液 + 原丝 → “海蛇皮”复合耐磨合股线"),
        new("craft_line_t8_oracle", "“偏光”深渊水色隐蔽前导", GearCraftSlot.Line, "“偏光”深渊水色隐蔽前导", GearTier.T8,
            [new FishRequirement("*", 2, FishRarity.Legendary)],
            [new(AlchemyMaterials.AbyssEssence, 2), new(AlchemyMaterials.NylonFilament, 8)],
            EconomySinks.AlchemyGearCraftT8Cost + 10000, 48, 36, null, 0, null, 0.75,
            "传说鱼×2 + 沧溟古鱼之髓 → “偏光”深渊水色隐蔽前导"),
        new("craft_lure_t8_oracle", "“疯狂乌贼”发光触须拖钓饵", GearCraftSlot.Lure, "“疯狂乌贼”发光触须拖钓饵", GearTier.T8,
            [new FishRequirement("*", 2, FishRarity.Legendary)],
            [new(AlchemyMaterials.AbyssGel, 5), new(AlchemyMaterials.MythScalePowder, 2)],
            EconomySinks.AlchemyGearCraftT8Cost, 48, 36, null, 0, null, 0.75,
            "传说鱼×2 + 凝胶 → “疯狂乌贼”发光触须拖钓饵×2"),
        new("craft_lure_t8_glow", "“闷响”内置钨珠避障小胖子", GearCraftSlot.Lure, "“闷响”内置钨珠避障小胖子", GearTier.T8,
            [new FishRequirement("暗流刺盖鱼", 1, FishRarity.Epic, "沉船墓场")],
            [new(AlchemyMaterials.WreckRust, 5), new(AlchemyMaterials.MythScalePowder, 2)],
            EconomySinks.AlchemyGearCraftT8Cost + 12000, 48, 36, null, 0, null, 0.75,
            "墓场史诗 + 铁锈 → “闷响”内置钨珠避障小胖子×2"),

        // ── T9 四槽（远礁许可+神话1 · 钓鱼55 · 猫42）──
        new("craft_rod_t9_final", "“万象归一”碳纤维终极枪柄", GearCraftSlot.Rod, "“万象归一”碳纤维终极枪柄", GearTier.T9,
            [new FishRequirement("神话·“远海沧龙”", 1, FishRarity.Legendary, "远礁外海")],
            [new(AlchemyMaterials.OpenSeaStarCore, 5), new(AlchemyMaterials.MythScalePowder, 4)],
            EconomySinks.AlchemyGearCraftT9Cost, 55, 42, null, 0, "远礁外海", 0,
            "远海神话 + 落星陨铁晶核×5 → “万象归一”碳纤维终极枪柄", RequiredMythicCaught: 1),
        new("craft_rod_t9_void", "“裂隙”高维编织便携旅竿", GearCraftSlot.Rod, "“裂隙”高维编织便携旅竿", GearTier.T9,
            [new FishRequirement("大洋金鳞鲷", 1, FishRarity.Legendary, "远礁外海")],
            [new(AlchemyMaterials.OpenSeaStarCore, 4), new(AlchemyMaterials.AbyssEssence, 3)],
            EconomySinks.AlchemyGearCraftT9Cost + 15000, 55, 42, null, 0, "远礁外海", 0,
            "远礁传说 + 星核 → “裂隙”高维编织便携旅竿", RequiredMythicCaught: 1),
        new("craft_reel_t9_final", "“极限”航天级阳极氧化飞线轮", GearCraftSlot.Reel, "“极限”航天级阳极氧化飞线轮", GearTier.T9,
            [],
            [new(AlchemyMaterials.GearSet, 7), new(AlchemyMaterials.OpenSeaStarCore, 3), new(AlchemyMaterials.Bearing, 5)],
            EconomySinks.AlchemyGearCraftT9Cost, 55, 42, null, 0, "远礁外海", 0,
            "星核 + 生锈齿轮组 → “极限”航天级阳极氧化飞线轮", RequiredMythicCaught: 1),
        new("craft_reel_t9_void", "“脉冲交互”微调双煞水滴", GearCraftSlot.Reel, "“脉冲交互”微调双煞水滴", GearTier.T9,
            [new FishRequirement("飞翼蝠鲼", 1, FishRarity.Epic, "远礁外海")],
            [new(AlchemyMaterials.OpenSeaStarCore, 2), new(AlchemyMaterials.GearSet, 5)],
            EconomySinks.AlchemyGearCraftT9Cost + 12000, 55, 42, null, 0, "远礁外海", 0,
            "远礁史诗 + 星核 → “脉冲交互”微调双煞水滴", RequiredMythicCaught: 1),
        new("craft_line_t9_final", "“极细”十二编超顺滑PE线", GearCraftSlot.Line, "“极细”十二编超顺滑PE线", GearTier.T9,
            [new FishRequirement("*", 2, FishRarity.Legendary, "远礁外海")],
            [new(AlchemyMaterials.OpenSeaStarCore, 4), new(AlchemyMaterials.CarbonFiber, 6)],
            EconomySinks.AlchemyGearCraftT9Cost, 55, 42, null, 0, "远礁外海", 0,
            "远礁传说×2 + 星核 → “极细”十二编超顺滑PE线", RequiredMythicCaught: 1),
        new("craft_line_t9_void", "“零延展”纳米级碳晶线", GearCraftSlot.Line, "“零延展”纳米级碳晶线", GearTier.T9,
            [new FishRequirement("蓝鳍金枪鱼", 2, FishRarity.Epic, "远礁外海")],
            [new(AlchemyMaterials.DragonResin, 4), new(AlchemyMaterials.OpenSeaStarCore, 3)],
            EconomySinks.AlchemyGearCraftT9Cost + 10000, 55, 42, null, 0, "远礁外海", 0,
            "远礁史诗×2 + 古树龙涎香 → “零延展”纳米级碳晶线", RequiredMythicCaught: 1),
        new("craft_lure_t9_final", "“极速羽毛”低阻防缠绕飞蝇", GearCraftSlot.Lure, "“极速羽毛”低阻防缠绕飞蝇", GearTier.T9,
            [new FishRequirement("神话·“金鳞海皇”", 1, FishRarity.Legendary, "远礁外海")],
            [new(AlchemyMaterials.OpenSeaStarCore, 5), new(AlchemyMaterials.MythScalePowder, 5)],
            EconomySinks.AlchemyGearCraftT9Cost, 55, 42, null, 0, "远礁外海", 0,
            "金鳞神话 + 星核 → “极速羽毛”低阻防缠绕飞蝇×2", RequiredMythicCaught: 1),
        new("craft_lure_t9_void", "“幻影”多节仿生活性多段鱼", GearCraftSlot.Lure, "“幻影”多节仿生活性多段鱼", GearTier.T9,
            [new FishRequirement("深水海鳝", 3, FishRarity.Rare, "远礁外海")],
            [new(AlchemyMaterials.DragonResin, 5), new(AlchemyMaterials.OpenSeaStarCore, 3)],
            EconomySinks.AlchemyGearCraftT9Cost + 14000, 55, 42, null, 0, "远礁外海", 0,
            "远礁稀有×3 + 古树龙涎香 → “幻影”多节仿生活性多段鱼×2", RequiredMythicCaught: 1),

        // ── T10 四槽（全图鉴95%+全神话 · 钓鱼60 · 猫50）──
        new("craft_rod_t10_whale", "“利维坦之握”海钓金枪重竿", GearCraftSlot.Rod, "“利维坦之握”海钓金枪重竿", GearTier.T10,
            [new FishRequirement("神话·“远海沧龙”", 1, FishRarity.Legendary, "远礁外海")],
            [new(AlchemyMaterials.VoidFiber, 6), new(AlchemyMaterials.OpenSeaStarCore, 5), new(AlchemyMaterials.MythScalePowder, 8)],
            EconomySinks.AlchemyGearCraftT10Cost, 60, 50, null, 0, null, 0.95,
            "神话鱼 + 裂隙虚空丝线×6 → “利维坦之握”海钓金枪重竿", RequiredAllMythic: true),
        new("craft_rod_t10_dragon", "“太弦”反重力微导架抛投竿", GearCraftSlot.Rod, "“太弦”反重力微导架抛投竿", GearTier.T10,
            [new FishRequirement("异变·“镜湖水虎兽”", 1, FishRarity.Legendary, "镇外溪流"),
             new FishRequirement("神话·“远海沧龙”", 1, FishRarity.Legendary, "远礁外海")],
            [new(AlchemyMaterials.VoidFiber, 8), new(AlchemyMaterials.MythScalePowder, 10)],
            EconomySinks.AlchemyGearCraftT10Cost + 50000, 60, 50, null, 0, null, 0.95,
            "双神话 + 裂隙虚空丝线×8 → “太弦”反重力微导架抛投竿", RequiredAllMythic: true),
        new("craft_reel_t10_ultimate", "“怒潮”数字闭环电绞轮", GearCraftSlot.Reel, "“怒潮”数字闭环电绞轮", GearTier.T10,
            [],
            [new(AlchemyMaterials.GearSet, 8), new(AlchemyMaterials.VoidFiber, 5), new(AlchemyMaterials.Bearing, 6)],
            EconomySinks.AlchemyGearCraftT10Cost, 60, 50, null, 0, null, 0.95,
            "裂隙虚空丝线 + 生锈齿轮组 → “怒潮”数字闭环电绞轮", RequiredAllMythic: true),
        new("craft_reel_t10_dragon", "“天枢”磁悬浮无摩擦线轴轮", GearCraftSlot.Reel, "“天枢”磁悬浮无摩擦线轴轮", GearTier.T10,
            [new FishRequirement("极光冰川巨鳎", 1, FishRarity.Legendary, "极光冰湾")],
            [new(AlchemyMaterials.VoidFiber, 4), new(AlchemyMaterials.AbyssEssence, 4)],
            EconomySinks.AlchemyGearCraftT10Cost + 40000, 60, 50, null, 0, null, 0.95,
            "冰湾传说 + 裂隙虚空丝线 → “天枢”磁悬浮无摩擦线轴轮", RequiredAllMythic: true),
        new("craft_line_t10_quantum", "“空天”高分子超密分子线", GearCraftSlot.Line, "“空天”高分子超密分子线", GearTier.T10,
            [new FishRequirement("*", 3, FishRarity.Legendary)],
            [new(AlchemyMaterials.VoidFiber, 6), new(AlchemyMaterials.MythScalePowder, 6)],
            EconomySinks.AlchemyGearCraftT10Cost, 60, 50, null, 0, null, 0.95,
            "传说鱼×3 + 裂隙虚空丝线 → “空天”高分子超密分子线", RequiredAllMythic: true),
        new("craft_line_t10_dragon", "“永恒”钛晶编织超耐磨巨线", GearCraftSlot.Line, "“永恒”钛晶编织超耐磨巨线", GearTier.T10,
            [new FishRequirement("异变·“雾海古神鱿”", 1, FishRarity.Legendary, "近海礁石")],
            [new(AlchemyMaterials.VoidFiber, 5), new(AlchemyMaterials.AbyssEssence, 5)],
            EconomySinks.AlchemyGearCraftT10Cost + 45000, 60, 50, null, 0, null, 0.95,
            "雾海神话 + 裂隙虚空丝线 → “永恒”钛晶编织超耐磨巨线", RequiredAllMythic: true),
        new("craft_lure_t10_quantum", "“终极撕裂者”深海巨型波扒", GearCraftSlot.Lure, "“终极撕裂者”深海巨型波扒", GearTier.T10,
            [new FishRequirement("神话·“极光霜龙”", 1, FishRarity.Legendary, "极光冰湾")],
            [new(AlchemyMaterials.VoidFiber, 6), new(AlchemyMaterials.MythScalePowder, 8)],
            EconomySinks.AlchemyGearCraftT10Cost, 60, 50, null, 0, null, 0.95,
            "霜龙神话 + 裂隙虚空丝线 → “终极撕裂者”深海巨型波扒×2", RequiredAllMythic: true),
        new("craft_lure_t10_dragon", "“星海之光”变频自发光仿生饵", GearCraftSlot.Lure, "“星海之光”变频自发光仿生饵", GearTier.T10,
            [new FishRequirement("异变·“白化巨螈”", 1, FishRarity.Legendary, "地下暗河")],
            [new(AlchemyMaterials.VoidFiber, 5), new(AlchemyMaterials.OpenSeaStarCore, 4), new(AlchemyMaterials.MythScalePowder, 6)],
            EconomySinks.AlchemyGearCraftT10Cost + 50000, 60, 50, null, 0, null, 0.95,
            "引渠神话 + 裂隙虚空丝线 → “星海之光”变频自发光仿生饵×2", RequiredAllMythic: true),
    ];
}
