namespace CyberPetApp.Models;

/// <summary>T6~T10 装备目录与炼金配方（500h 毕业曲线：T8 图鉴75% · T10 图鉴95%+全神话）。</summary>
internal static class GearT6T10Data
{
    internal static readonly RodSpec[] ExtraRods =
    [
        new("引渠星陨竿", 4.2, 115, 5, 38, 0, "炼金 T6 · 引渠特化", GearTier.T6, ShopAvailable: false, CraftOnly: true, RequiredLicenseSpot: "地下暗河", RequiredCatLevel: 24),
        new("星陨折叠竿", 4.5, 125, 5, 40, 0, "炼金 T6 · 敏锐+45%", GearTier.T6, ShopAvailable: false, CraftOnly: true, RequiredDexSpot: "地下暗河", RequiredDexPercent: 0.55, RequiredCatLevel: 24),
        new("冰湾虚空竿", 4.8, 140, 5, 46, 0, "炼金 T7 · 冰湾特化", GearTier.T7, ShopAvailable: false, CraftOnly: true, RequiredLicenseSpot: "极光冰湾", RequiredCatLevel: 30),
        new("虚空战竿", 5.0, 150, 5, 48, 0, "炼金 T7 · 深层+敏锐", GearTier.T7, ShopAvailable: false, CraftOnly: true, RequiredDexSpot: "极光冰湾", RequiredDexPercent: 0.60, RequiredCatLevel: 30),
        new("沧溟龙脊竿", 5.3, 165, 5, 54, 0, "炼金 T8 · 钓重165kg", GearTier.T8, ShopAvailable: false, CraftOnly: true, RequiredOverallDexPercent: 0.75, RequiredCatLevel: 36),
        new("冰湾神谕竿", 5.1, 158, 5, 52, 0, "炼金 T8 · 冰湾神话向", GearTier.T8, ShopAvailable: false, CraftOnly: true, RequiredOverallDexPercent: 0.75, RequiredLicenseSpot: "极光冰湾", RequiredCatLevel: 36),
        new("神谕终焉竿", 5.6, 185, 5, 60, 0, "炼金 T9 · 敏锐+56%", GearTier.T9, ShopAvailable: false, CraftOnly: true, RequiredOverallDexPercent: 0.85, RequiredCatLevel: 42, RequiredMythicCaught: 1),
        new("虚空折叠竿", 5.8, 195, 5, 62, 0, "炼金 T9 · 抛投5+", GearTier.T9, ShopAvailable: false, CraftOnly: true, RequiredOverallDexPercent: 0.85, RequiredLicenseSpot: "远礁外海", RequiredCatLevel: 42, RequiredMythicCaught: 1),
        new("虚鲸终极竿", 6.2, 220, 5, 68, 0, "终极竿 · 抛投5 · 钓重220kg", GearTier.T10, ShopAvailable: false, CraftOnly: true, RequiredOverallDexPercent: 0.95, RequiredCatLevel: 50, RequiredAllMythic: true),
        new("沧龙神谕竿", 6.5, 250, 5, 70, 0, "毕业竿 · 神话素材终极", GearTier.T10, ShopAvailable: false, CraftOnly: true, RequiredOverallDexPercent: 0.95, RequiredCatLevel: 50, RequiredAllMythic: true),
    ];

    internal static readonly ReelSpec[] ExtraReels =
    [
        new("引渠液压轮", 14, 9.2, 62, 0.86, 38, 0, "炼金 T6 · 线杯62kg", GearTier.T6, ShopAvailable: false, CraftOnly: true, RequiredLicenseSpot: "地下暗河", RequiredCatLevel: 24),
        new("星陨接口轮", 15, 9.8, 68, 0.89, 40, 0, "炼金 T6 · 高顺滑", GearTier.T6, ShopAvailable: false, CraftOnly: true, RequiredDexSpot: "地下暗河", RequiredDexPercent: 0.55, RequiredCatLevel: 24),
        new("冰湾虚空轮", 17, 10.2, 75, 0.91, 46, 0, "炼金 T7 · 冰湾轮", GearTier.T7, ShopAvailable: false, CraftOnly: true, RequiredLicenseSpot: "极光冰湾", RequiredCatLevel: 30),
        new("虚空液压轮", 18, 10.5, 82, 0.93, 48, 0, "炼金 T7 · 卸力强化", GearTier.T7, ShopAvailable: false, CraftOnly: true, RequiredDexSpot: "极光冰湾", RequiredDexPercent: 0.60, RequiredCatLevel: 30),
        new("沧溟纺车轮", 20, 11.0, 95, 0.94, 54, 0, "炼金 T8 · 线杯95kg", GearTier.T8, ShopAvailable: false, CraftOnly: true, RequiredOverallDexPercent: 0.75, RequiredCatLevel: 36),
        new("神谕刹车轮", 19, 10.8, 90, 0.93, 52, 0, "炼金 T8 · 冰湾特化轮", GearTier.T8, ShopAvailable: false, CraftOnly: true, RequiredOverallDexPercent: 0.75, RequiredCatLevel: 36),
        new("终焉接口轮", 22, 11.5, 110, 0.96, 60, 0, "炼金 T9 · 线杯110kg", GearTier.T9, ShopAvailable: false, CraftOnly: true, RequiredOverallDexPercent: 0.85, RequiredLicenseSpot: "远礁外海", RequiredCatLevel: 42, RequiredMythicCaught: 1),
        new("虚空神经轮", 21, 11.2, 105, 0.95, 62, 0, "炼金 T9 · 远礁向", GearTier.T9, ShopAvailable: false, CraftOnly: true, RequiredOverallDexPercent: 0.85, RequiredLicenseSpot: "远礁外海", RequiredCatLevel: 42, RequiredMythicCaught: 1),
        new("终极液压轮", 24, 12.0, 130, 0.98, 68, 0, "毕业轮 · 线杯130kg", GearTier.T10, ShopAvailable: false, CraftOnly: true, RequiredOverallDexPercent: 0.95, RequiredCatLevel: 50, RequiredAllMythic: true),
        new("沧龙神谕轮", 23, 11.8, 125, 0.97, 70, 0, "毕业轮 · 神话卸力", GearTier.T10, ShopAvailable: false, CraftOnly: true, RequiredOverallDexPercent: 0.95, RequiredCatLevel: 50, RequiredAllMythic: true),
    ];

    internal static readonly LineSpec[] ExtraLines =
    [
        new("引渠星陨线", 75, 1.9, 0.20, 0.52, WaterDepth.Deep, 38, 0, "炼金 T6 · 强度75kg", GearTier.T6, ShopAvailable: false, CraftOnly: true, RequiredLicenseSpot: "地下暗河", RequiredCatLevel: 24),
        new("星陨编织线", 80, 2.0, 0.22, 0.55, WaterDepth.Deep, 40, 0, "炼金 T6 · 耐磨55%", GearTier.T6, ShopAvailable: false, CraftOnly: true, RequiredDexSpot: "地下暗河", RequiredDexPercent: 0.55, RequiredCatLevel: 24),
        new("冰湾虚空线", 95, 2.1, 0.24, 0.58, WaterDepth.Deep, 46, 0, "炼金 T7 · 强度95kg", GearTier.T7, ShopAvailable: false, CraftOnly: true, RequiredLicenseSpot: "极光冰湾", RequiredCatLevel: 30),
        new("虚空导流线", 100, 2.2, 0.26, 0.60, WaterDepth.Deep, 48, 0, "炼金 T7 · 高敏锐", GearTier.T7, ShopAvailable: false, CraftOnly: true, RequiredDexSpot: "极光冰湾", RequiredDexPercent: 0.60, RequiredCatLevel: 30),
        new("沧溟龙筋线", 120, 2.4, 0.28, 0.65, WaterDepth.Deep, 54, 0, "炼金 T8 · 强度120kg", GearTier.T8, ShopAvailable: false, CraftOnly: true, RequiredOverallDexPercent: 0.75, RequiredCatLevel: 36),
        new("神谕编织线", 115, 2.3, 0.27, 0.63, WaterDepth.Deep, 52, 0, "炼金 T8 · 冰湾线", GearTier.T8, ShopAvailable: false, CraftOnly: true, RequiredOverallDexPercent: 0.75, RequiredCatLevel: 36),
        new("终焉丝导线", 145, 2.6, 0.30, 0.70, WaterDepth.Deep, 60, 0, "炼金 T9 · 强度145kg", GearTier.T9, ShopAvailable: false, CraftOnly: true, RequiredOverallDexPercent: 0.85, RequiredLicenseSpot: "远礁外海", RequiredCatLevel: 42, RequiredMythicCaught: 1),
        new("虚空龙筋线", 150, 2.7, 0.32, 0.72, WaterDepth.Deep, 62, 0, "炼金 T9 · 耐磨72%", GearTier.T9, ShopAvailable: false, CraftOnly: true, RequiredOverallDexPercent: 0.85, RequiredLicenseSpot: "远礁外海", RequiredCatLevel: 42, RequiredMythicCaught: 1),
        new("终极量子线", 180, 2.9, 0.35, 0.78, WaterDepth.Deep, 68, 0, "毕业线 · 强度180kg", GearTier.T10, ShopAvailable: false, CraftOnly: true, RequiredOverallDexPercent: 0.95, RequiredCatLevel: 50, RequiredAllMythic: true),
        new("沧龙神谕线", 200, 3.0, 0.38, 0.80, WaterDepth.Deep, 70, 0, "毕业线 · 神话耐磨", GearTier.T10, ShopAvailable: false, CraftOnly: true, RequiredOverallDexPercent: 0.95, RequiredCatLevel: 50, RequiredAllMythic: true),
    ];

    internal static readonly LureSpec[] ExtraLures =
    [
        new("引渠星陨饵", 0.48, 1.1, WaterDepth.Deep, 8, 38, 2, 0, "炼金 T6 · 品质+110%", GearTier.T6, ShopAvailable: false, CraftOnly: true, RequiredLicenseSpot: "地下暗河", RequiredCatLevel: 24),
        new("星陨磷光饵", 0.52, 1.25, WaterDepth.Deep, 7, 40, 2, 0, "炼金 T6 · 引渠特化饵", GearTier.T6, ShopAvailable: false, CraftOnly: true, RequiredDexSpot: "地下暗河", RequiredDexPercent: 0.55, RequiredCatLevel: 24, MythicBonus: 0.03),
        new("冰湾虚空饵", 0.56, 1.35, WaterDepth.Deep, 7, 46, 2, 0, "炼金 T7 · 品质+135%", GearTier.T7, ShopAvailable: false, CraftOnly: true, RequiredLicenseSpot: "极光冰湾", RequiredCatLevel: 30, MythicBonus: 0.04),
        new("虚空拟态饵", 0.58, 1.45, WaterDepth.Deep, 6, 48, 2, 0, "炼金 T7 · 深层 lure", GearTier.T7, ShopAvailable: false, CraftOnly: true, RequiredDexSpot: "极光冰湾", RequiredDexPercent: 0.60, RequiredCatLevel: 30, MythicBonus: 0.05),
        new("沧溟神谕饵", 0.60, 1.55, WaterDepth.Deep, 5, 54, 2, 0, "炼金 T8 · 神话饵率+6%", GearTier.T8, ShopAvailable: false, CraftOnly: true, RequiredOverallDexPercent: 0.75, RequiredCatLevel: 36, MythicBonus: 0.06),
        new("龙筋幽光饵", 0.58, 1.50, WaterDepth.Deep, 6, 52, 2, 0, "炼金 T8 · 冰湾饵", GearTier.T8, ShopAvailable: false, CraftOnly: true, RequiredOverallDexPercent: 0.75, RequiredCatLevel: 36, MythicBonus: 0.05),
        new("终焉鳞粉饵", 0.62, 1.65, WaterDepth.Deep, 5, 60, 2, 0, "炼金 T9 · 神话饵率+7%", GearTier.T9, ShopAvailable: false, CraftOnly: true, RequiredOverallDexPercent: 0.85, RequiredLicenseSpot: "远礁外海", RequiredCatLevel: 42, RequiredMythicCaught: 1, MythicBonus: 0.07),
        new("虚空神谕饵", 0.64, 1.75, WaterDepth.Deep, 4, 62, 2, 0, "炼金 T9 · 远礁向", GearTier.T9, ShopAvailable: false, CraftOnly: true, RequiredOverallDexPercent: 0.85, RequiredLicenseSpot: "远礁外海", RequiredCatLevel: 42, RequiredMythicCaught: 1, MythicBonus: 0.08),
        new("终极量子饵", 0.68, 1.90, WaterDepth.Deep, 4, 68, 2, 0, "毕业饵 · 神话饵率+10%", GearTier.T10, ShopAvailable: false, CraftOnly: true, RequiredOverallDexPercent: 0.95, RequiredCatLevel: 50, RequiredAllMythic: true, MythicBonus: 0.10),
        new("沧龙神谕饵", 0.70, 2.00, WaterDepth.Deep, 3, 70, 2, 0, "毕业饵 · 神话终极", GearTier.T10, ShopAvailable: false, CraftOnly: true, RequiredOverallDexPercent: 0.95, RequiredCatLevel: 50, RequiredAllMythic: true, MythicBonus: 0.12),
    ];

    internal static readonly GearCraftRecipe[] ExtraCraftRecipes =
    [
        // ── T6 四槽（引渠许可 · 钓鱼32 · 猫24）──
        new("craft_rod_t6_canal", "引渠星陨竿", GearCraftSlot.Rod, "引渠星陨竿", GearTier.T6,
            [new FishRequirement("地下金丝鲃", 1, FishRarity.Legendary, "地下暗河")],
            [new(AlchemyMaterials.CanalGlowPowder, 4), new(AlchemyMaterials.CarbonFiber, 4), new(AlchemyMaterials.Resin, 2)],
            EconomySinks.AlchemyGearCraftT6Cost, 32, 24, null, 0, "地下暗河", 0,
            "引渠传说 + 引渠荧光粉×4 → 引渠星陨竿"),
        new("craft_rod_t6_star", "星陨折叠竿", GearCraftSlot.Rod, "星陨折叠竿", GearTier.T6,
            [new FishRequirement("彩光鲑", 1, FishRarity.Epic, "地下暗河")],
            [new(AlchemyMaterials.StarfallAlloy, 3), new(AlchemyMaterials.CanalGlowPowder, 3)],
            EconomySinks.AlchemyGearCraftT6Cost + 3000, 32, 24, "地下暗河", 0.55, null, 0,
            "引渠史诗 + 星陨合金 → 星陨折叠竿"),
        new("craft_reel_t6_canal", "引渠液压轮", GearCraftSlot.Reel, "引渠液压轮", GearTier.T6,
            [],
            [new(AlchemyMaterials.GearSet, 4), new(AlchemyMaterials.CanalGlowPowder, 3), new(AlchemyMaterials.Bearing, 2)],
            EconomySinks.AlchemyGearCraftT6Cost, 32, 24, null, 0, "地下暗河", 0,
            "荧光粉 + 齿轮组 → 引渠液压轮"),
        new("craft_reel_t6_star", "星陨接口轮", GearCraftSlot.Reel, "星陨接口轮", GearTier.T6,
            [new FishRequirement("夜光鲈", 2, FishRarity.Rare, "地下暗河")],
            [new(AlchemyMaterials.GearSet, 3), new(AlchemyMaterials.StarfallAlloy, 2)],
            EconomySinks.AlchemyGearCraftT6Cost + 2000, 32, 24, "地下暗河", 0.55, null, 0,
            "引渠稀有×2 + 星陨合金 → 星陨接口轮"),
        new("craft_line_t6_canal", "引渠星陨线", GearCraftSlot.Line, "引渠星陨线", GearTier.T6,
            [],
            [new(AlchemyMaterials.NylonFilament, 8), new(AlchemyMaterials.CanalGlowPowder, 4)],
            EconomySinks.AlchemyGearCraftT6Cost, 32, 24, null, 0, "地下暗河", 0,
            "荧光粉 + 尼龙原丝 → 引渠星陨线"),
        new("craft_line_t6_star", "星陨编织线", GearCraftSlot.Line, "星陨编织线", GearTier.T6,
            [new FishRequirement("*", 3, FishRarity.Rare, "地下暗河")],
            [new(AlchemyMaterials.StarfallAlloy, 3), new(AlchemyMaterials.NylonFilament, 5)],
            EconomySinks.AlchemyGearCraftT6Cost, 32, 24, "地下暗河", 0.55, null, 0,
            "引渠稀有×3 + 星陨合金 → 星陨编织线"),
        new("craft_lure_t6_canal", "引渠星陨饵", GearCraftSlot.Lure, "引渠星陨饵", GearTier.T6,
            [new FishRequirement("*", 4, FishRarity.Rare, "地下暗河")],
            [new(AlchemyMaterials.CanalGlowPowder, 5), new(AlchemyMaterials.ScalePowder, 4)],
            EconomySinks.AlchemyGearCraftT6Cost, 32, 24, null, 0, "地下暗河", 0,
            "引渠稀有×4 + 荧光粉 → 引渠星陨饵×2"),
        new("craft_lure_t6_star", "星陨磷光饵", GearCraftSlot.Lure, "星陨磷光饵", GearTier.T6,
            [new FishRequirement("盲眼洞螈", 1, FishRarity.Epic, "地下暗河")],
            [new(AlchemyMaterials.StarfallAlloy, 4), new(AlchemyMaterials.ScalePowder, 5)],
            EconomySinks.AlchemyGearCraftT6Cost + 2500, 32, 24, "地下暗河", 0.55, null, 0,
            "引渠史诗 + 星陨合金 → 星陨磷光饵×2"),

        // ── T7 四槽（冰湾许可 · 钓鱼40 · 猫30）──
        new("craft_rod_t7_void", "冰湾虚空竿", GearCraftSlot.Rod, "冰湾虚空竿", GearTier.T7,
            [new FishRequirement("霜龙传说鱼", 1, FishRarity.Legendary, "极光冰湾")],
            [new(AlchemyMaterials.AuroraIceCrystal, 4), new(AlchemyMaterials.CarbonFiber, 5)],
            EconomySinks.AlchemyGearCraftT7Cost, 40, 30, null, 0, "极光冰湾", 0,
            "冰湾传说 + 极光冰晶×4 → 冰湾虚空竿"),
        new("craft_rod_t7_battle", "虚空战竿", GearCraftSlot.Rod, "虚空战竿", GearTier.T7,
            [new FishRequirement("冰川巨鲈", 1, FishRarity.Epic, "极光冰湾")],
            [new(AlchemyMaterials.VoidCore, 3), new(AlchemyMaterials.AuroraIceCrystal, 2)],
            EconomySinks.AlchemyGearCraftT7Cost + 5000, 40, 30, "极光冰湾", 0.60, null, 0,
            "冰湾史诗 + 虚空原核 → 虚空战竿"),
        new("craft_reel_t7_void", "冰湾虚空轮", GearCraftSlot.Reel, "冰湾虚空轮", GearTier.T7,
            [],
            [new(AlchemyMaterials.GearSet, 5), new(AlchemyMaterials.AuroraIceCrystal, 3), new(AlchemyMaterials.Bearing, 3)],
            EconomySinks.AlchemyGearCraftT7Cost, 40, 30, null, 0, "极光冰湾", 0,
            "冰晶 + 齿轮组 → 冰湾虚空轮"),
        new("craft_reel_t7_hydro", "虚空液压轮", GearCraftSlot.Reel, "虚空液压轮", GearTier.T7,
            [new FishRequirement("冰纹银鳗", 1, FishRarity.Epic, "极光冰湾")],
            [new(AlchemyMaterials.VoidCore, 2), new(AlchemyMaterials.GearSet, 3)],
            EconomySinks.AlchemyGearCraftT7Cost + 4000, 40, 30, "极光冰湾", 0.60, null, 0,
            "冰湾史诗 + 虚空原核 → 虚空液压轮"),
        new("craft_line_t7_void", "冰湾虚空线", GearCraftSlot.Line, "冰湾虚空线", GearTier.T7,
            [],
            [new(AlchemyMaterials.NylonFilament, 10), new(AlchemyMaterials.AuroraIceCrystal, 4)],
            EconomySinks.AlchemyGearCraftT7Cost, 40, 30, null, 0, "极光冰湾", 0,
            "冰晶 + 尼龙原丝 → 冰湾虚空线"),
        new("craft_line_t7_guide", "虚空导流线", GearCraftSlot.Line, "虚空导流线", GearTier.T7,
            [new FishRequirement("*", 2, FishRarity.Epic, "极光冰湾")],
            [new(AlchemyMaterials.VoidCore, 3), new(AlchemyMaterials.CarbonFiber, 4)],
            EconomySinks.AlchemyGearCraftT7Cost, 40, 30, "极光冰湾", 0.60, null, 0,
            "冰湾史诗×2 + 虚空原核 → 虚空导流线"),
        new("craft_lure_t7_void", "冰湾虚空饵", GearCraftSlot.Lure, "冰湾虚空饵", GearTier.T7,
            [new FishRequirement("*", 3, FishRarity.Rare, "极光冰湾")],
            [new(AlchemyMaterials.AuroraIceCrystal, 4), new(AlchemyMaterials.ScalePowder, 5)],
            EconomySinks.AlchemyGearCraftT7Cost, 40, 30, null, 0, "极光冰湾", 0,
            "冰湾稀有×3 + 冰晶 → 冰湾虚空饵×2"),
        new("craft_lure_t7_mimic", "虚空拟态饵", GearCraftSlot.Lure, "虚空拟态饵", GearTier.T7,
            [new FishRequirement("寒渊巨口鱼", 1, FishRarity.Epic, "极光冰湾")],
            [new(AlchemyMaterials.VoidCore, 3), new(AlchemyMaterials.MythScalePowder, 1)],
            EconomySinks.AlchemyGearCraftT7Cost + 6000, 40, 30, "极光冰湾", 0.60, null, 0,
            "冰湾史诗 + 虚空原核 → 虚空拟态饵×2"),

        // ── T8 四槽（全图鉴75% · 钓鱼48 · 猫36）──
        new("craft_rod_t8_dragon", "沧溟龙脊竿", GearCraftSlot.Rod, "沧溟龙脊竿", GearTier.T8,
            [new FishRequirement("深湾巨口鲨", 1, FishRarity.Legendary, "远礁外海")],
            [new(AlchemyMaterials.AbyssGel, 5), new(AlchemyMaterials.DeepSeaCrystal, 4), new(AlchemyMaterials.MythScalePowder, 2)],
            EconomySinks.AlchemyGearCraftT8Cost, 48, 36, null, 0, null, 0.75,
            "远礁传说 + 深渊凝胶 → 沧溟龙脊竿"),
        new("craft_rod_t8_oracle", "冰湾神谕竿", GearCraftSlot.Rod, "冰湾神谕竿", GearTier.T8,
            [new FishRequirement("亡魂旗鱼", 1, FishRarity.Epic, "沉船墓场")],
            [new(AlchemyMaterials.WreckRust, 6), new(AlchemyMaterials.AbyssGel, 3)],
            EconomySinks.AlchemyGearCraftT8Cost, 48, 36, null, 0, null, 0.75,
            "墓场史诗 + 沉船铁锈 → 冰湾神谕竿"),
        new("craft_reel_t8_abyss", "沧溟纺车轮", GearCraftSlot.Reel, "沧溟纺车轮", GearTier.T8,
            [],
            [new(AlchemyMaterials.GearSet, 6), new(AlchemyMaterials.AbyssGel, 3), new(AlchemyMaterials.Bearing, 4)],
            EconomySinks.AlchemyGearCraftT8Cost, 48, 36, null, 0, null, 0.75,
            "深渊凝胶 + 齿轮组 → 沧溟纺车轮"),
        new("craft_reel_t8_oracle", "神谕刹车轮", GearCraftSlot.Reel, "神谕刹车轮", GearTier.T8,
            [new FishRequirement("墓场幽灵鲨", 1, FishRarity.Epic, "沉船墓场")],
            [new(AlchemyMaterials.GearSet, 4), new(AlchemyMaterials.WreckRust, 4)],
            EconomySinks.AlchemyGearCraftT8Cost + 8000, 48, 36, null, 0, null, 0.75,
            "墓场史诗 + 铁锈 → 神谕刹车轮"),
        new("craft_line_t8_dragon", "沧溟龙筋线", GearCraftSlot.Line, "沧溟龙筋线", GearTier.T8,
            [],
            [new(AlchemyMaterials.NylonFilament, 12), new(AlchemyMaterials.AbyssGel, 4)],
            EconomySinks.AlchemyGearCraftT8Cost, 48, 36, null, 0, null, 0.75,
            "深渊凝胶 + 原丝 → 沧溟龙筋线"),
        new("craft_line_t8_oracle", "神谕编织线", GearCraftSlot.Line, "神谕编织线", GearTier.T8,
            [new FishRequirement("*", 2, FishRarity.Legendary)],
            [new(AlchemyMaterials.AbyssEssence, 2), new(AlchemyMaterials.NylonFilament, 8)],
            EconomySinks.AlchemyGearCraftT8Cost + 10000, 48, 36, null, 0, null, 0.75,
            "传说鱼×2 + 沧溟神髓 → 神谕编织线"),
        new("craft_lure_t8_oracle", "沧溟神谕饵", GearCraftSlot.Lure, "沧溟神谕饵", GearTier.T8,
            [new FishRequirement("*", 2, FishRarity.Legendary)],
            [new(AlchemyMaterials.AbyssGel, 5), new(AlchemyMaterials.MythScalePowder, 2)],
            EconomySinks.AlchemyGearCraftT8Cost, 48, 36, null, 0, null, 0.75,
            "传说鱼×2 + 凝胶 → 沧溟神谕饵×2"),
        new("craft_lure_t8_glow", "龙筋幽光饵", GearCraftSlot.Lure, "龙筋幽光饵", GearTier.T8,
            [new FishRequirement("暗流旗鱼", 1, FishRarity.Epic, "沉船墓场")],
            [new(AlchemyMaterials.WreckRust, 5), new(AlchemyMaterials.MythScalePowder, 2)],
            EconomySinks.AlchemyGearCraftT8Cost + 12000, 48, 36, null, 0, null, 0.75,
            "墓场史诗 + 铁锈 → 龙筋幽光饵×2"),

        // ── T9 四槽（远礁许可+神话1 · 钓鱼55 · 猫42）──
        new("craft_rod_t9_final", "神谕终焉竿", GearCraftSlot.Rod, "神谕终焉竿", GearTier.T9,
            [new FishRequirement("神话·远海沧龙", 1, FishRarity.Legendary, "远礁外海")],
            [new(AlchemyMaterials.OpenSeaStarCore, 5), new(AlchemyMaterials.MythScalePowder, 4)],
            EconomySinks.AlchemyGearCraftT9Cost, 55, 42, null, 0, "远礁外海", 0,
            "远海神话 + 外海星核×5 → 神谕终焉竿", RequiredMythicCaught: 1),
        new("craft_rod_t9_void", "虚空折叠竿", GearCraftSlot.Rod, "虚空折叠竿", GearTier.T9,
            [new FishRequirement("金鳞锦鲤", 1, FishRarity.Legendary, "远礁外海")],
            [new(AlchemyMaterials.OpenSeaStarCore, 4), new(AlchemyMaterials.AbyssEssence, 3)],
            EconomySinks.AlchemyGearCraftT9Cost + 15000, 55, 42, null, 0, "远礁外海", 0,
            "远礁传说 + 星核 → 虚空折叠竿", RequiredMythicCaught: 1),
        new("craft_reel_t9_final", "终焉接口轮", GearCraftSlot.Reel, "终焉接口轮", GearTier.T9,
            [],
            [new(AlchemyMaterials.GearSet, 7), new(AlchemyMaterials.OpenSeaStarCore, 3), new(AlchemyMaterials.Bearing, 5)],
            EconomySinks.AlchemyGearCraftT9Cost, 55, 42, null, 0, "远礁外海", 0,
            "星核 + 齿轮组 → 终焉接口轮", RequiredMythicCaught: 1),
        new("craft_reel_t9_void", "虚空神经轮", GearCraftSlot.Reel, "虚空神经轮", GearTier.T9,
            [new FishRequirement("远礁蝠鲼", 1, FishRarity.Epic, "远礁外海")],
            [new(AlchemyMaterials.OpenSeaStarCore, 2), new(AlchemyMaterials.GearSet, 5)],
            EconomySinks.AlchemyGearCraftT9Cost + 12000, 55, 42, null, 0, "远礁外海", 0,
            "远礁史诗 + 星核 → 虚空神经轮", RequiredMythicCaught: 1),
        new("craft_line_t9_final", "终焉丝导线", GearCraftSlot.Line, "终焉丝导线", GearTier.T9,
            [new FishRequirement("*", 2, FishRarity.Legendary, "远礁外海")],
            [new(AlchemyMaterials.OpenSeaStarCore, 4), new(AlchemyMaterials.CarbonFiber, 6)],
            EconomySinks.AlchemyGearCraftT9Cost, 55, 42, null, 0, "远礁外海", 0,
            "远礁传说×2 + 星核 → 终焉丝导线", RequiredMythicCaught: 1),
        new("craft_line_t9_void", "虚空龙筋线", GearCraftSlot.Line, "虚空龙筋线", GearTier.T9,
            [new FishRequirement("深湾金枪", 2, FishRarity.Epic, "远礁外海")],
            [new(AlchemyMaterials.DragonResin, 4), new(AlchemyMaterials.OpenSeaStarCore, 3)],
            EconomySinks.AlchemyGearCraftT9Cost + 10000, 55, 42, null, 0, "远礁外海", 0,
            "远礁史诗×2 + 龙息树脂 → 虚空龙筋线", RequiredMythicCaught: 1),
        new("craft_lure_t9_final", "终焉鳞粉饵", GearCraftSlot.Lure, "终焉鳞粉饵", GearTier.T9,
            [new FishRequirement("神话·金鳞海皇", 1, FishRarity.Legendary, "远礁外海")],
            [new(AlchemyMaterials.OpenSeaStarCore, 5), new(AlchemyMaterials.MythScalePowder, 5)],
            EconomySinks.AlchemyGearCraftT9Cost, 55, 42, null, 0, "远礁外海", 0,
            "金鳞神话 + 星核 → 终焉鳞粉饵×2", RequiredMythicCaught: 1),
        new("craft_lure_t9_void", "虚空神谕饵", GearCraftSlot.Lure, "虚空神谕饵", GearTier.T9,
            [new FishRequirement("深流银鳗", 3, FishRarity.Rare, "远礁外海")],
            [new(AlchemyMaterials.DragonResin, 5), new(AlchemyMaterials.OpenSeaStarCore, 3)],
            EconomySinks.AlchemyGearCraftT9Cost + 14000, 55, 42, null, 0, "远礁外海", 0,
            "远礁稀有×3 + 龙息树脂 → 虚空神谕饵×2", RequiredMythicCaught: 1),

        // ── T10 四槽（全图鉴95%+全神话 · 钓鱼60 · 猫50）──
        new("craft_rod_t10_whale", "虚鲸终极竿", GearCraftSlot.Rod, "虚鲸终极竿", GearTier.T10,
            [new FishRequirement("神话·远海沧龙", 1, FishRarity.Legendary, "远礁外海")],
            [new(AlchemyMaterials.VoidFiber, 6), new(AlchemyMaterials.OpenSeaStarCore, 5), new(AlchemyMaterials.MythScalePowder, 8)],
            EconomySinks.AlchemyGearCraftT10Cost, 60, 50, null, 0, null, 0.95,
            "神话鱼 + 虚空纤维×6 → 虚鲸终极竿", RequiredAllMythic: true),
        new("craft_rod_t10_dragon", "沧龙神谕竿", GearCraftSlot.Rod, "沧龙神谕竿", GearTier.T10,
            [new FishRequirement("异变·巨型水虎鱼", 1, FishRarity.Legendary, "镇外溪流"),
             new FishRequirement("神话·远海沧龙", 1, FishRarity.Legendary, "远礁外海")],
            [new(AlchemyMaterials.VoidFiber, 8), new(AlchemyMaterials.MythScalePowder, 10)],
            EconomySinks.AlchemyGearCraftT10Cost + 50000, 60, 50, null, 0, null, 0.95,
            "双神话 + 虚空纤维×8 → 沧龙神谕竿", RequiredAllMythic: true),
        new("craft_reel_t10_ultimate", "终极液压轮", GearCraftSlot.Reel, "终极液压轮", GearTier.T10,
            [],
            [new(AlchemyMaterials.GearSet, 8), new(AlchemyMaterials.VoidFiber, 5), new(AlchemyMaterials.Bearing, 6)],
            EconomySinks.AlchemyGearCraftT10Cost, 60, 50, null, 0, null, 0.95,
            "虚空纤维 + 齿轮组 → 终极液压轮", RequiredAllMythic: true),
        new("craft_reel_t10_dragon", "沧龙神谕轮", GearCraftSlot.Reel, "沧龙神谕轮", GearTier.T10,
            [new FishRequirement("霜龙传说鱼", 1, FishRarity.Legendary, "极光冰湾")],
            [new(AlchemyMaterials.VoidFiber, 4), new(AlchemyMaterials.AbyssEssence, 4)],
            EconomySinks.AlchemyGearCraftT10Cost + 40000, 60, 50, null, 0, null, 0.95,
            "冰湾传说 + 虚空纤维 → 沧龙神谕轮", RequiredAllMythic: true),
        new("craft_line_t10_quantum", "终极量子线", GearCraftSlot.Line, "终极量子线", GearTier.T10,
            [new FishRequirement("*", 3, FishRarity.Legendary)],
            [new(AlchemyMaterials.VoidFiber, 6), new(AlchemyMaterials.MythScalePowder, 6)],
            EconomySinks.AlchemyGearCraftT10Cost, 60, 50, null, 0, null, 0.95,
            "传说鱼×3 + 虚空纤维 → 终极量子线", RequiredAllMythic: true),
        new("craft_line_t10_dragon", "沧龙神谕线", GearCraftSlot.Line, "沧龙神谕线", GearTier.T10,
            [new FishRequirement("异变·深海大王乌贼", 1, FishRarity.Legendary, "近海礁石")],
            [new(AlchemyMaterials.VoidFiber, 5), new(AlchemyMaterials.AbyssEssence, 5)],
            EconomySinks.AlchemyGearCraftT10Cost + 45000, 60, 50, null, 0, null, 0.95,
            "雾海神话 + 虚空纤维 → 沧龙神谕线", RequiredAllMythic: true),
        new("craft_lure_t10_quantum", "终极量子饵", GearCraftSlot.Lure, "终极量子饵", GearTier.T10,
            [new FishRequirement("神话·极光霜龙", 1, FishRarity.Legendary, "极光冰湾")],
            [new(AlchemyMaterials.VoidFiber, 6), new(AlchemyMaterials.MythScalePowder, 8)],
            EconomySinks.AlchemyGearCraftT10Cost, 60, 50, null, 0, null, 0.95,
            "霜龙神话 + 虚空纤维 → 终极量子饵×2", RequiredAllMythic: true),
        new("craft_lure_t10_dragon", "沧龙神谕饵", GearCraftSlot.Lure, "沧龙神谕饵", GearTier.T10,
            [new FishRequirement("异变·白化巨螈", 1, FishRarity.Legendary, "地下暗河")],
            [new(AlchemyMaterials.VoidFiber, 5), new(AlchemyMaterials.OpenSeaStarCore, 4), new(AlchemyMaterials.MythScalePowder, 6)],
            EconomySinks.AlchemyGearCraftT10Cost + 50000, 60, 50, null, 0, null, 0.95,
            "引渠神话 + 虚空纤维 → 沧龙神谕饵×2", RequiredAllMythic: true),
    ];
}
